
=encoding euc-jp

=head1 名前

Class::DBI::Column - テーブル内のカラム

=head1 概要

	my $column = Class::DBI::Column->new($name);

	my $name  = $column->name;

	my @groups = $column->groups;
	my $pri_col = $colg->primary;

	if ($column->in_database) { ... }

=head1 解説

Each Class::DBI class maintains a list of its columns as class data.
This provides an interface to those columns. You probably shouldn't be
dealing with this directly.

各Class::DBIクラスはクラスデータとして自身のカラムリストを維持する。
このモジュールはそれらのカラムに対するインターフェースを提供する。
恐らこのモジュールを直接扱うべきではない。

=head1 メソッド

=head2 new

	my $column = Class::DBI::Column->new($column)

A new object for this column.

このカラムのための新しいオブジェクト。

