
=head1 NAME

=begin original

if - C<use> a Perl module if a condition holds

=end original

条件を満たした時にだけ Perl モジュールを C<use> する

=head1 SYNOPSIS

  use if CONDITION, MODULE => ARGUMENTS;

=head1 DESCRIPTION

=begin original

The construct

=end original

The construct
(TBT)

  use if CONDITION, MODULE => ARGUMENTS;

=begin original

has no effect unless C<CONDITION> is true.  In this case the effect is
the same as of

=end original

has no effect unless C<CONDITION> is true.  In this case the effect is
the same as of
(TBT)

  use MODULE ARGUMENTS;

=begin original

Above C<< => >> provides necessary quoting of C<MODULE>.  If not used (e.g.,
no ARGUMENTS to give), you'd better quote C<MODULE> yourselves.

=end original

Above C<< => >> provides necessary quoting of C<MODULE>.  If not used (e.g.,
no ARGUMENTS to give), you'd better quote C<MODULE> yourselves.
(TBT)

=head1 BUGS

=begin original

The current implementation does not allow specification of the
required version of the module.

=end original

The current implementation does not allow specification of the
required version of the module.
(TBT)

=head1 AUTHOR

Ilya Zakharevich L<mailto:perl-module-if@ilyaz.org>.

=cut

