
=encoding euc-jp

=head1 NAME

=begin original

perlfaq2 - Obtaining and Learning about Perl

=end original

perlfaq2 - Perl の入手と学習

=head1 DESCRIPTION

=begin original

This section of the FAQ answers questions about where to find
source and documentation for Perl, support, and
related matters.

=end original

FAQ のこのセクションでは、Perl のソースや Perl に関するドキュメントが
手に入れられる場所に関する質問や、サポートとトレーニング、関連した
出来事に関する質問に回答しています。

=head2 What machines support perl?  Where do I get it?

(perl はどんなマシンで動きますか? どこで入手できますか?)

=begin original

The standard release of perl (the one maintained by the perl
development team) is distributed only in source code form.  You
can find the latest releases at http://www.cpan.org/src/README.html .

=end original

perlの標準リリース(perl 開発チームが保守しているもの)は
ソースコード形式でのみ配布されています。
最新版は http://www.cpan.org/src/README.html にあります。

=begin original

Perl builds and runs on a bewildering number of platforms.  Virtually
all known and current Unix derivatives are supported (perl's native
platform), as are other systems like VMS, DOS, OS/2, Windows,
QNX, BeOS, OS X, MPE/iX and the Amiga.

=end original

Perl は驚くほど多くのプラットフォームでビルドされ、実行されています。
このソースはほとんどの UNIX システム(perl の本来の環境)を
サポートしていますし、VMS, OS/2, Window, QNX, BeOS, MPE/iX, Amiga といった
その他のシステムもサポートしています。

=begin original

Binary distributions for some proprietary platforms can be found
http://www.cpan.org/ports/ directory. Because these are not part of
the standard distribution, they may and in fact do differ from the
base perl port in a variety of ways. You'll have to check their
respective release notes to see just what the differences are.  These
differences can be either positive (e.g. extensions for the features
of the particular platform that are not supported in the source
release of perl) or negative (e.g. might be based upon a less current
source release of perl).

=end original

幾つかの独占的システム用のバイナリ配布パッケージは
http://www.cpan.org/ports/
というディレクトリで見つけられます。
これらは標準配布パッケージには含まれていないので、様々な面で基本的な
perl の移植とは異なっています。
あなたはリリースノートを読んで、(標準のものと)なにが違っているのかを
確かめる必要があるでしょう。
そういった違いは、ポジティブなもの(標準リリースの perl では
サポートされていないような、プラットフォーム特有の機能に対する
拡張機能など)もあればネガティブなもの(最新の標準 perl にあまり
基づいていないものなど)もあるでしょう。

=head2 How can I get a binary version of perl?

(バイナリ形式の perl はどうすれば入手できますか?)

=begin original

(contributed by brian d foy)

=end original

(brian d foy によって寄贈されました)

=begin original

ActiveState: Windows, Linux, Mac OS X, Solaris, AIX and HP-UX

=end original

ActiveState: Windows, Linux, Mac OS X, Solaris, AIX, HP-UX

	http://www.activestate.com/

=begin original

Sunfreeware.com: Solaris 2.5 to Solaris 10 (SPARC and x86)

=end original

Sunfreeware.com: Solaris 2.5 から Solaris 10 (SPARC と x86)

	http://www.sunfreeware.com/

=begin original

Strawberry Perl: Windows, Perl 5.8.8 and 5.10.0

=end original

Strawberry Perl: Windows, Perl 5.8.8 と 5.10.0

	http://www.strawberryperl.com
	
IndigoPerl: Windows

	http://indigostar.com/

=head2 I don't have a C compiler. How can I build my own Perl interpreter?

(私は C コンパイラーを持っていません。どうすれば自分用の Perl インタプリタをビルドできますか?)

=begin original

Since you don't have a C compiler, you're doomed and your vendor
should be sacrificed to the Sun gods.  But that doesn't help you.

=end original

汝は C コンパイラーを持っていないが故に、汝は破滅し、汝のベンダーは
Sun の神に対する贄となるべし。
しかし、それは汝を救うことはない。

=begin original

What you need to do is get a binary version of C<gcc> for your system
first.  Consult the Usenet FAQs for your operating system for
information on where to get such a binary version.

=end original

あなたがする必要のあることは、まず始めにあなたの使っているシステム向けの
C<gcc> のバイナリを入手することです。
それを手に入れる場所については、あなたの使っているオペレーティング
システム向けの Usenet FAQ をあたってください。

=begin original

You might look around the net for a pre-built binary of Perl (or a
C compiler!) that meets your needs, though:

=end original

ニーズを満たすような Perl (または C コンパイラ!) のビルド済みバイナリを
ネットで探す必要があるかもしれませんが:

=begin original

For Windows, Vanilla Perl ( http://vanillaperl.com/ ) and Strawberry Perl
( http://strawberryperl.com/ ) come with a
bundled C compiler. ActivePerl is a pre-compiled version of Perl
ready-to-use.

=end original

Windows 用としては、Vanilla Perl ( http://vanillaperl.com/ ) と
Strawberry Perl ( http://strawberryperl.com/ ) は、C コンパイラとセットに
なっています。
ActivePerl はコンパイル済みですぐ使える Perl です。

=begin original

For Sun systems, SunFreeware.com provides binaries of most popular
applications, including compilers and Perl.

=end original

Sun のシステム用には、SunFreeware.com が、コンパイラと Perl を含む、
もっとも有名なアプリケーションのバイナリを提供しています。

=head2 I copied the perl binary from one machine to another, but scripts don't work.

(perl のバイナリをあるマシンから別のマシンにコピーしたのだけど、スクリプトが動きませんでした)

=begin original

That's probably because you forgot libraries, or library paths differ.
You really should build the whole distribution on the machine it will
eventually live on, and then type C<make install>.  Most other
approaches are doomed to failure.

=end original

それは多分、ライブラリをコピーするのを忘れたか、ライブラリパスが
違っているのでしょう。
実際に使用するマシンの上で配布パッケージ全体から
ビルドをして、その後に C<make install> とタイプするようにすべきです。
他のやり方ではほとんど失敗してしまうでしょう。

=begin original

One simple way to check that things are in the right place is to print out
the hard-coded C<@INC> that perl looks through for libraries:

=end original

正しい場所がどこなのかを確かめる単純な方法の一つは、perl が
ライブラリを検索する場所がハードコードされている C<@INC> を出力することです。

    % perl -le 'print for @INC'

=begin original

If this command lists any paths that don't exist on your system, then you
may need to move the appropriate libraries to these locations, or create
symbolic links, aliases, or shortcuts appropriately.  C<@INC> is also printed as
part of the output of

=end original

もしこのコマンドの出力にあなたのシステムはないパスが含まれていたら、
適切なライブラリをそういった場所に移すか、シンボリックリンク、
エイリアス、ショートカットといったものを作成する必要があるでしょう。
C<@INC> はまた以下のようにしても出力されます:

    % perl -V

=begin original

You might also want to check out
L<perlfaq8/"How do I keep my own module/library directory?">.

=end original

L<perlfaq8/"How do I keep my own module/library directory?"> も
チェックしておいたほうが良いかもしれません。

=head2 I grabbed the sources and tried to compile but gdbm/dynamic loading/malloc/linking/... failed.  How do I make it work?

(ソースを取ってきてコンパイルしようとしたのだけど、gdbm/dynamic loading/malloc/linking/... failed.  となってしまった。動くようにするにはどうすればいいの?)

=begin original

Read the F<INSTALL> file, which is part of the source distribution.
It describes in detail how to cope with most idiosyncrasies that the
C<Configure> script can't work around for any given system or
architecture.

=end original

ソースの配布パッケージに入っていた F<INSTALL> というファイルを読んでください。
そこには一部のシステムやアーキテクチャーにおいて C<Configure> スクリプトが
動作しないという問題のほとんどの場合に対処する方法が説明されています。

=head2 What modules and extensions are available for Perl?  What is CPAN?  What does CPAN/src/... mean?

(Perlに使えるモジュールとかエクステンションってなんですか? CPAN ってなに? CPAN/src/... ってどういう意味なんですか?)

=begin original

CPAN stands for Comprehensive Perl Archive Network, a multi-gigabyte
archive replicated on hundreds of machines all over the world. CPAN
contains source code, non-native ports, documentation, scripts, and
many third-party modules and extensions, designed for everything from
commercial database interfaces to keyboard/screen control to web
walking and CGI scripts. The master web site for CPAN is
http://www.cpan.org/ and there is the CPAN Multiplexer at
http://www.cpan.org/CPAN.html which will choose a mirror near you via
DNS.  See http://www.perl.com/CPAN (without a slash at the end) for
how this process works. Also, http://mirror.cpan.org/ has a nice
interface to the http://www.cpan.org/MIRRORED.BY mirror directory.

=end original

CPAN は Comprehensive Perl Archive Network (総合 Perl アーカイブ
ネットワーク)の略で、これは世界中にある数百のマシン上の数ギガバイトの
アーカイブの写しです。
CPAN にはソースコード、ネイティブでない移植、ドキュメント、スクリプト、
多くのサードパーティーによるモジュールやエクステンションが収められていて、
商用データベースから web ウォーキングを制御するキーボード/スクリーン
インターフェースと CGI スクリプトでデザインされています。
CPAN のメインウェブサイトは http://www.cpan.org/ にあります;
また CPAN Multipler http://www.cpan.org/CPAN.html を使うと DNS 経由で
あなたの近くになるミラーサイトを選ぶことができます。
これがどう動いているかは
http://www.perl.com/CPAN (最後のスラッシュはありません) を見てください。
また、http://mirror.cpan.org/ は http://www.cpan.org/MIRRORED.BY
ミラーディレクトリへのよいインターフェースを提供しています。

=begin original

See the CPAN FAQ at http://www.cpan.org/misc/cpan-faq.html for answers
to the most frequently asked questions about CPAN including how to
become a mirror.

=end original

CPAN についてのよくある質問や、ミラーになる方法については、
CPAN FAQ http://www.cpan.org/misc/cpan-faq.html を参照してください。

=begin original

C<CPAN/path/...> is a naming convention for files available on CPAN
sites.  CPAN indicates the base directory of a CPAN mirror, and the
rest of the path is the path from that directory to the file. For
instance, if you're using ftp://ftp.funet.fi/pub/languages/perl/CPAN
as your CPAN site, the file C<CPAN/misc/japh> is downloadable as
ftp://ftp.funet.fi/pub/languages/perl/CPAN/misc/japh .

=end original

C<CPAN/path/...> は CPAN サイト上で入手できるファイルに対する名前づけの
規則です。
CPAN は CPAN のミラーリングしている基準ディレクトリを示し、パスの
残りの部分はそのディレクトリからファイルへの相対パスを示します。
たとえば、ftp://ftp.funet.fi/pub/languages/perl/CPAN があなたの
使っている CPAN サイトだとすると、C<CPAN/misc/japh> というファイルは
ftp://ftp.funet.fi/pub/languages/perl/CPAN/misc/japh から
ダウンロードできます。

=begin original

Considering that, as of 2006, there are over ten thousand existing
modules in the archive, one probably exists to do nearly anything you
can think of. Current categories under C<CPAN/modules/by-category/>
include Perl core modules; development support; operating system
interfaces; networking, devices, and interprocess communication; data
type utilities; database interfaces; user interfaces; interfaces to
other languages; filenames, file systems, and file locking;
internationalization and locale; world wide web support; server and
daemon utilities; archiving and compression; image manipulation; mail
and news; control flow utilities; filehandle and I/O; Microsoft
Windows modules; and miscellaneous modules.

=end original

アーカイブには 2006 年時点で 10000 以上のモジュールが既にあると
いうことを考えれば、あなたが考えるようなものに近いものがあるという
可能性があります。
C<CPAN/modules/by-category/> の下のカテゴリーは現在のところ、Perl
コアモジュール、開発サポート、オペレーティングシステムインターフェース、
ネットワーク、デバイス、プロセス間通信、データ型ユーティリティ、
データベースインターフェース、ユーザーインターフェース、
他の言語に対するインターフェース、ファイル名、ファイルシステム、
ファイルのロック、国際化とロケール、
ワールドワイドウェブのサポート、サーバーやデーモンのユーティリティ、
アーカイブと圧縮、イメージ操作、メールやニューズ、制御フロー
ユーティリティ、ファイルハンドルと I/O、Microsoft Windows モジュール、
その他といったものが含まれます。

=begin original

See http://www.cpan.org/modules/00modlist.long.html or
http://search.cpan.org/ for a more complete list of modules by
category.

=end original

カテゴリ別のモジュールのより完全なリストについては
http://www.cpan.org/modules/00modlist.long.html か
http://search.cpan.org/ を参照してください。

=begin original

CPAN is a free service and is not affiliated with O'Reilly Media.

=end original

CPAN はフリーなサービスで、O'Reilly Media との関連はありません。

=head2 Is there an ISO or ANSI certified version of Perl?

(ISO や ANSI で認証された Perl はあるの?)

=begin original

Certainly not.  Larry expects that he'll be certified before Perl is.

=end original

現時点ではありません。
Larry は Perl より先に自分が認証されるだろうと考えています。

=head2 Where can I get information on Perl?

(Perl に関する情報はどこで手に入れられますか?)

=begin original

The complete Perl documentation is available with the Perl distribution.
If you have Perl installed locally, you probably have the documentation
installed as well: type C<man perl> if you're on a system resembling Unix.
This will lead you to other important man pages, including how to set your
C<$MANPATH>.  If you're not on a Unix system, access to the documentation
will be different; for example, documentation might only be in HTML format.  All
proper perl installations have fully-accessible documentation.

=end original

Perl に関する完全なドキュメントは Perl の配布パッケージに含まれています。
あなたが Perl をローカルにインストールしたのなら、ドキュメントも同様に
インストールされているでしょう。
あなたの使っているシステムが UNIX に似たものであるなら、
C<man perl> とタイプしてみてください。
C<$MANPATH> の設定方法を含め、これは他の重要なマニュアルページへ
導くものとなるでしょう。
あなたの使っている UNIX でないのであれば、ドキュメントにアクセスするのには
違った方法になります。
たとえば、HTMLフォーマットのドキュメントだけが使えるかもしれません。
すべての適切な perl のインストールでは完全にアクセス可能な
ドキュメントが存在します。

=begin original

You might also try C<perldoc perl> in case your system doesn't
have a proper C<man> command, or it's been misinstalled.  If that doesn't
work, try looking in C</usr/local/lib/perl5/pod> for documentation.

=end original

あなたの使っているシステムに適当な C<man> コマンドがなければ、
C<perldoc perl> を試してみてください。
これが駄目ならインストールはうまく行っていません。
もしうまく行かなかったのなら、C</usr/local/lib/perl5/pod> にある
ドキュメントを探してみてください。

=begin original

If all else fails, consult http://perldoc.perl.org/ which has the
complete documentation in HTML and PDF format.

=end original

今までの方法が全部失敗してしまったなら、HTML と PDF フォーマットの
完全なドキュメントが収められている
http://perldoc.perl.org/ を参照してください。

=begin original

Many good books have been written about Perl--see the section later in
L<perlfaq2> for more details.

=end original

Perl について書かれた多くの良書があります--詳しくは
L<perlfaq2> で後述する章を参照してください。

=begin original

Tutorial documents are included in current or upcoming Perl releases
include L<perltoot> for objects or L<perlboot> for a beginner's
approach to objects, L<perlopentut> for file opening semantics,
L<perlreftut> for managing references, L<perlretut> for regular
expressions, L<perlthrtut> for threads, L<perldebtut> for debugging,
and L<perlxstut> for linking C and Perl together.  There may be more
by the time you read this.  These URLs might also be useful:

=end original

チュートリアルは Perl のリリースに含まれていて、オブジェクトの
チュートリアルは L<perltoot>、
初心者向けのオブジェクトへのアプローチは L<perlboot>、
ファイルのオープンに関するものは L<perlopentut>、
リファレンスの管理は L<perlreftut>、
正規表現に関しては L<perlretut>、
スレッドに関しては L<perlthrtut>、
デバッグに関しては L<perldebtut>、
C と Perl とのリンクは L<perlxstut> にあります。
これを読むことによって得るものは多いでしょう。
以下の URL も有用でしょう:

    http://perldoc.perl.org/
    http://bookmarks.cpan.org/search.cgi?cat=Training%2FTutorials

=head2 What are the Perl newsgroups on Usenet?  Where do I post questions?

(Usenet にある Perl のニューズグループはなに? 質問はどこに投稿するの?)

=begin original

Several groups devoted to the Perl language are on Usenet:

=end original

Usenet には Perl 言語に関連するいくつかのグループがあります:

=begin original

	comp.lang.perl.announce      Moderated announcement group
	comp.lang.perl.misc          High traffic general Perl discussion
	comp.lang.perl.moderated     Moderated discussion group
	comp.lang.perl.modules       Use and development of Perl modules
	comp.lang.perl.tk            Using Tk (and X) from Perl

=end original

	comp.lang.perl.announce      モデレートされたアナウンス用グループ
	comp.lang.perl.misc          流量の多い Perl に関する一般的な議論
	comp.lang.perl.moderated     モデレートされた議論用グループ
	comp.lang.perl.modules       Perl モジュールの使用と開発
	comp.lang.perl.tk            Perl から Tk(と X)を使う

=begin original

Some years ago, comp.lang.perl was divided into those groups, and
comp.lang.perl itself officially removed.  While that group may still
be found on some news servers, it is unwise to use it, because
postings there will not appear on news servers which honour the
official list of group names.  Use comp.lang.perl.misc for topics
which do not have a more-appropriate specific group.

=end original

数年前、comp.lang.perl はこれらのグループに分割され、comp.lang.perl は
公式に削除されました。
まだこのグループが存在するサーバーもありますが、
これを使うのは賢明とは言えません。
なぜならここに投稿されたものは公式なグループ名のリストに従っている
ニュースサーバーには現れないからです。
より適切な特有のグループがない話題については comp.lang.perl.misc を
使ってください。

=begin original

There is also a Usenet gateway to Perl mailing lists sponsored by
perl.org at nntp://nntp.perl.org , a web interface to the same lists
at http://nntp.perl.org/group/ and these lists are also available
under the C<perl.*> hierarchy at http://groups.google.com . Other
groups are listed at http://lists.perl.org/ ( also known as
http://lists.cpan.org/ ).

=end original

perl.org が提供している Perl メイリングリストの Usenet ゲートウェイが
nntp://nntp.perl.org に、この web インターフェースが
http://nntp.perl.org/group/ にあります。
また、これらのリストは http://groups.google.com の C<perl.*> 階層からも
利用可能です。その他のグループは http://lists.perl.org/
( http://lists.cpan.org/ としても知られています) に一覧があります。

=begin original

A nice place to ask questions is the PerlMonks site,
http://www.perlmonks.org/ , or the Perl Beginners mailing list
http://lists.perl.org/showlist.cgi?name=beginners .

=end original

質問をするのによい場所は PerlMonks サイト http://www.perlmonks.org/ または
Perl Beginners メイリングリスト
http://lists.perl.org/showlist.cgi?name=beginners です。

=begin original

Note that none of the above are supposed to write your code for you:
asking questions about particular problems or general advice is fine,
but asking someone to write your code for free is not very cool.

=end original

上記のどれも自分のために自分のコードを書いてくれることを
想定していないことに注意してください。
特定の問題や一般的なアドバイスを得るのはよいことです。
しかし無料でだれかに自分のためのコードを書いてくれるように頼むのは
感心しません。

=head2 Where should I post source code?

(ソースコードはどこに投稿すべきなのですか?)

=begin original

You should post source code to whichever group is most appropriate, but
feel free to cross-post to comp.lang.perl.misc.  If you want to cross-post
to alt.sources, please make sure it follows their posting standards,
including setting the Followup-To header line to NOT include alt.sources;
see their FAQ ( http://www.faqs.org/faqs/alt-sources-intro/ ) for details.

=end original

最も適切なグループに投稿すべきですが、comp.lang.perl.misc へ
クロスポストするのはあなたの自由です。
もしあなたが alt.sources にもクロスポストしたいのならそこの投稿規則に従って、
alt.sources を B<含まない> Followup-To ヘッダーを設定してください。
詳しくは(投稿に関する) FAQ
( http://www.faqs.org/faqs/alt-sources-intro/ ) を参照してください。

=begin original

If you're just looking for software, first use Google
( http://www.google.com ), Google's Usenet search interface
( http://groups.google.com ),  and CPAN Search ( http://search.cpan.org ).
This is faster and more productive than just posting a request.

=end original

もしあなたが単にソフトウェアを探しているだけならば、まず最初に Google
(http://www.google.com ), Google の Usenet 検索
インターフェース ( http://groups.google.com ),
CPAN Search (http://search.cpan.org ) をあたってみましょう。
それが、探し物の投稿をするよりも速くて生産的なやり方です。

=head2 Perl Books

(Perl の書籍)

=begin original

A number of books on Perl and/or CGI programming are available.  A few
of these are good, some are OK, but many aren't worth your money.
There is a list of these books, some with extensive reviews, at
http://books.perl.org/ . If you don't see your book listed here, you
can write to perlfaq-workers@perl.org .

=end original

Perl や CGI プログラミングに関する本はたくさん入手可能です。
そのうちの幾つかは良く(good)、一部はまあまあ(OK)といったところですが多くは
お金を出すほどの価値がありません。
http://books.perl.org/ には、いくつかのレビュー付きの本のリストが
あります。
もしあなたの本がこのリストにないなら、perlfaq-workers@perl.org に
書くことができます。

=begin original

The incontestably definitive reference book on Perl, written by
the creator of Perl, is Programming Perl:

=end original

Perl の創造者によって書かれた Perl に関する本の決定版は、
Programming Perl です:

=begin original

	Programming Perl (the "Camel Book"):
	by Larry Wall, Tom Christiansen, and Jon Orwant
	ISBN 0-596-00027-8  [3rd edition July 2000]
	http://www.oreilly.com/catalog/pperl3/
	(English, translations to several languages are also available)

=end original

	Programming Perl (ラクダ本):
	by Larry Wall, Tom Christiansen, and Jon Orwant
	ISBN 0-596-00027-8  (英語版)
	ISBN 4873110963     (日本語版第一巻)
	ISBN 4873110971     (日本語版第二巻)
	http://www.oreilly.com/catalog/pperl3/
	(English, translations to several languages are also available)

=begin original

The companion volume to the Camel containing thousands
of real-world examples, mini-tutorials, and complete programs is:

=end original

現実世界の例、小さなチュートリアル、完全なプログラムを
たくさん収録した、ラクダ本の副読本としては以下のものがあります:

=begin original

	The Perl Cookbook (the "Ram Book"):
	by Tom Christiansen and Nathan Torkington,
	    with Foreword by Larry Wall
	ISBN 0-596-00313-7 [2nd Edition August 2003]
	http://www.oreilly.com/catalog/perlckbk2/

=end original

	Perl クックブック (the "Ram Book"):
	by Tom Christiansen and Nathan Torkington,
	    with Foreword by Larry Wall
	ISBN 0-596-00313-7 [2nd Edition August 2003]
	http://www.oreilly.com/catalog/perlckbk2/
	ISBN 4-87311-202-8 (日本語版第一巻)
	http://www.oreilly.co.jp/books/4873112028/
	ISBN 4-87311-203-6 (日本語版第二巻)
	http://www.oreilly.co.jp/books/4873112036/

=begin original

If you're already a seasoned programmer, then the Camel Book might
suffice for you to learn Perl.  If you're not, check out the
Llama book:

=end original

もしあなたがすでに経験を積んだシステムプログラマーであるなら、
ラクダ本で十分かもしれません。
もしそうでないのならリャマ本が良いでしょう:

=begin original

	Learning Perl
	by Randal L. Schwartz, Tom Phoenix, and brian d foy
	ISBN 0-596-10105-8 [4th edition July 2005]
	http://www.oreilly.com/catalog/learnperl4/

=end original

	初めての Perl
	by Randal L. Schwartz, Tom Phoenix, and brian d foy
	ISBN 0-596-10105-8 [4th edition July 2005]
	http://www.oreilly.com/catalog/learnperl4/
	ISBN 4-87311-126-9 (第三版日本語版)
	http://www.oreilly.co.jp/books/4873111269/

=begin original

And for more advanced information on writing larger programs,
presented in the same style as the Llama book, continue your education
with the Alpaca book:

=end original

リャマ本と同じスタイルで、より大きなプログラムを書くためのより
進んだ情報を得るためには、アルパカ本で勉強を続けるのがよいでしょう:

=begin original

	Intermediate Perl (the "Alpaca Book")
	by Randal L. Schwartz and brian d foy, with Tom Phoenix (foreword by Damian Conway)
	ISBN 0-596-10206-2 [1st edition March 2006]
	http://www.oreilly.com/catalog/lrnperlorm/

=end original

	続・初めての Perl 改訂版 (アルパカ本)
	by Randal L. Schwartz and brian d foy, with Tom Phoenix (foreword by Damian Conway)
	ISBN 0-596-10206-2 [1st edition March 2006]
	http://www.oreilly.com/catalog/lrnperlorm/
	ISBN 4-87311-305-9 (日本語版)
	http://www.oreilly.co.jp/books/4873113059/

=begin original

Addison-Wesley ( http://www.awlonline.com/ ) and Manning
( http://www.manning.com/ ) are also publishers of some fine Perl books
such as I<Object Oriented Programming with Perl> by Damian Conway and
I<Network Programming with Perl> by Lincoln Stein.

=end original

Addison-Wesley ( http://www.awlonline.com/ ) と Manning
( http://www.manning.com/ ) もまた
Damian Conway による I<Object Oriented Programming with Perl> や
Lincoln Stein による I<Network Programming with Perl> といった
素晴らしい Perl 本を出版しています。

=begin original

An excellent technical book discounter is Bookpool at
http://www.bookpool.com/ where a 30% discount or more is not unusual.

=end original

素晴らしい技術書の安売り屋である Bookpool
( http://www.bookpool.com/ ) では 30% 以上の値引きも
珍しくありません。

=begin original

What follows is a list of the books that the FAQ authors found personally
useful.  Your mileage may (but, we hope, probably won't) vary.

=end original

以下に挙げたリストは、FAQ の作者たちが個人的に便利だと思う本のリストです。
あなたの見方は違ったものかもしれません(が、そうではないと
私たちは願っています)。

=begin original

Recommended books on (or mostly on) Perl follow.

=end original

Perl に関連していてお薦めの本は以下の通りです。

=over 4

=item References

	Programming Perl
	by Larry Wall, Tom Christiansen, and Jon Orwant
	ISBN 0-596-00027-8 [3rd edition July 2000]
	http://www.oreilly.com/catalog/pperl3/

	Perl 5 Pocket Reference
	by Johan Vromans
	ISBN 0-596-00374-9 [4th edition July 2002]
	http://www.oreilly.com/catalog/perlpr4/

=item Tutorials

	Beginning Perl
	by James Lee
	ISBN 1-59059-391-X [2nd edition August 2004]
	http://apress.com/book/bookDisplay.html?bID=344

	Elements of Programming with Perl
	by Andrew L. Johnson
	ISBN 1-884777-80-5 [1st edition October 1999]
	http://www.manning.com/johnson/

	Learning Perl
	by Randal L. Schwartz, Tom Phoenix, and brian d foy
	ISBN 0-596-52010-7 [5th edition June 2008]
	http://oreilly.com/catalog/9780596520106/

	Intermediate Perl (the "Alpaca Book")
	by Randal L. Schwartz and brian d foy, with Tom Phoenix (foreword by Damian Conway)
	ISBN 0-596-10206-2 [1st edition March 2006]
	http://www.oreilly.com/catalog/intermediateperl/

	Mastering Perl
	by brian d foy
	ISBN 0-596-52724-1 [1st edition July 2007]
	http://www.oreilly.com/catalog/9780596527242/

=item Task-Oriented

	Writing Perl Modules for CPAN
	by Sam Tregar
	ISBN 1-59059-018-X [1st edition August 2002]
	http://apress.com/book/bookDisplay.html?bID=14

	The Perl Cookbook
	by Tom Christiansen and Nathan Torkington
	    with foreword by Larry Wall
	ISBN 1-56592-243-3 [1st edition August 1998]
	http://www.oreilly.com/catalog/cookbook/

	Effective Perl Programming
	by Joseph Hall
	ISBN 0-201-41975-0 [1st edition 1998]
	http://www.awl.com/

	Real World SQL Server Administration with Perl
	by Linchi Shea
	ISBN 1-59059-097-X [1st edition July 2003]
	http://apress.com/book/bookDisplay.html?bID=171

=item Special Topics

	Perl Best Practices
	by Damian Conway
	ISBN: 0-596-00173-8 [1st edition July 2005]
	http://www.oreilly.com/catalog/perlbp/

	Higher Order Perl
	by Mark-Jason Dominus
	ISBN: 1558607013 [1st edition March 2005]
	http://hop.perl.plover.com/

	Perl 6 Now: The Core Ideas Illustrated with Perl 5
	by Scott Walters
	ISBN 1-59059-395-2 [1st edition December 2004]
	http://apress.com/book/bookDisplay.html?bID=355

	Mastering Regular Expressions
	by Jeffrey E. F. Friedl
	ISBN 0-596-00289-0 [2nd edition July 2002]
	http://www.oreilly.com/catalog/regex2/

	Network Programming with Perl
	by Lincoln Stein
	ISBN 0-201-61571-1 [1st edition 2001]
	http://www.awlonline.com/

	Object Oriented Perl
	by Damian Conway
	    with foreword by Randal L. Schwartz
	ISBN 1-884777-79-1 [1st edition August 1999]
	http://www.manning.com/conway/

	Data Munging with Perl
	by Dave Cross
	ISBN 1-930110-00-6 [1st edition 2001]
	http://www.manning.com/cross

	Mastering Perl/Tk
	by Steve Lidie and Nancy Walsh
	ISBN 1-56592-716-8 [1st edition January 2002]
	http://www.oreilly.com/catalog/mastperltk/

	Extending and Embedding Perl
	by Tim Jenness and Simon Cozens
	ISBN 1-930110-82-0 [1st edition August 2002]
	http://www.manning.com/jenness

	Perl Debugger Pocket Reference
	by Richard Foley
	ISBN 0-596-00503-2 [1st edition January 2004]
	http://www.oreilly.com/catalog/perldebugpr/

	Pro Perl Debugging
	by Richard Foley with Andy Lester
	ISBN 1-59059-454-1 [1st edition July 2005]
	http://www.apress.com/book/view/1590594541

=back

=head2 Which magazines have Perl content?

(Perl 関連の雑誌は?)

=begin original

I<The Perl Review> ( http://www.theperlreview.com ) focuses on Perl
almost completely (although it sometimes sneaks in an article about
another language). There's also I<$foo Magazin>, a german magazine
dedicated to Perl, at ( http://www.foo-magazin.de ).

=end original

I<The Perl Review> ( http://www.theperlreview.com ) はほとんど完全に Perl を
対象としています(しかし時々他の言語に関する記事もあります)。
I<$foo Magazin> という Perl 専門のドイツ語の雑誌も
( http://www.foo-magazin.de ) にあります。

=begin original

The I<Perl-Zeitung> is a German-speaking magazine for Perl beginners
(see http://perl-zeitung.at.tf ).

=end original

I<Perl-Zeitung> は Perl 初心者のためのドイツ語の雑誌です
(http://perl-zeitung.at.tf を参照してください)。

=begin original

Magazines that frequently carry quality articles on Perl include I<The
Perl Review> ( http://www.theperlreview.com ), I<Unix Review> (
http://www.unixreview.com/ ), I<Linux Magazine> (
http://www.linuxmagazine.com/ ), and Usenix's newsletter/magazine to
its members, I<login:> ( http://www.usenix.org/ ).

=end original

Perl に関する高品質の記事を頻繁に掲載しているものとしては
I<The Perl Review> ( http://www.theperlreview.com ),
I<Unix Review> ( http://www.unixreview.com/ ),
I<Linux Magazine> ( http://www.linuxmagazine.com/ )と、
そして Usenix のメンバーに対する
newsletter/magazine である I<login:>( http://www.usenix.org/ )
などがあります。

=begin original

The Perl columns of Randal L. Schwartz are available on the web at
http://www.stonehenge.com/merlyn/WebTechniques/ ,
http://www.stonehenge.com/merlyn/UnixReview/ , and
http://www.stonehenge.com/merlyn/LinuxMag/ .

=end original

Randal L. Schwartz の Perl コラムは以下で読むことが出来ます:
http://www.stonehenge.com/merlyn/WebTechniques/ ,
http://www.stonehenge.com/merlyn/UnixReview/ , 
http://www.stonehenge.com/merlyn/LinuxMag/

=begin original

The first (and for a long time, only) periodical devoted to All Things
Perl, I<The Perl Journal> contains tutorials, demonstrations, case
studies, announcements, contests, and much more.  I<TPJ> has columns
on web development, databases, Win32 Perl, graphical programming,
regular expressions, and networking, and sponsors the Obfuscated Perl
Contest and the Perl Poetry Contests.  Beginning in November 2002, I<TPJ>
moved to a reader-supported monthly e-zine format in which subscribers
can download issues as PDF documents. In 2006, I<TPJ> merged with Dr.
Dobbs Journal (online edition). To read old I<TPJ> articles, see
http://www.ddj.com/ .

=end original

最初の(そして長い間唯一の) Perl 専門誌である I<Perl Jounal>には、
チュートリアル、デモ、ケーススタディ、アナウンス、などなどたくさんあります。
I<TPJ>には web 開発、データベース、Win32 版 Perl、
グラフィックプログラミング、正規表現、ネットワークに関するコラムがあり、
難解な Perl コンテスト(Obfuscated Perl Contest)と
Perl 詩コンテストのスポンサーです。
2002 年 11 月始めに、I<TPJ> は読者が支える月間の e-zine 形式となり、
購読者は PDF ドキュメントとしてダウンロードできます。
2006 年に、I<TPJ> は Dr.Dobbs Journal (online edition) と合併しました。
古い I<TPJ> の記事を読むには、http://www.ddj.com/ を参照してください。

=head2 What mailing lists are there for Perl?

(Perlのためのメイリングリストって?)

=begin original

Most of the major modules (C<Tk>, C<CGI>, C<libwww-perl>) have their own
mailing lists.  Consult the documentation that came with the module for
subscription information.

=end original

主なモジュール(C<Tk>, C<CGI>, C<libwww-perl>)はそれぞれのメイリングリストが
あります。それぞれのモジュールに付属している申し込み情報を
調べてみてください。

=begin original

A comprehensive list of Perl related mailing lists can be found at:

=end original

Perl に関連するメイリングリストの網羅的なリストは以下で見つかります。

	http://lists.perl.org/

=head2 Where are the archives for comp.lang.perl.misc?

(comp.lang.perl.misc のアーカイブはどこにありますか?)

=begin original

The Google search engine now carries archived and searchable newsgroup
content.

=end original

Google 検索エンジンは現在ニュースグループのコンテンツも収集し、
検索可能になっています。

=begin original

http://groups.google.com/group/comp.lang.perl.misc/topics

=end original

http://groups.google.com/group/comp.lang.perl.misc/topics

=begin original

If you have a question, you can be sure someone has already asked the
same question at some point on c.l.p.m. It requires some time and patience
to sift through all the content but often you will find the answer you
seek.

=end original

何か質問がある場合、他の人が同じ質問を c.l.p.m でしていないか確認できます。
これには多少の時間がかかり、全てのコンテンツを調べるのに忍耐が必要ですが、
しばしば探していた答えが見つかります。

=head2 Where can I buy a commercial version of perl?

(どこで商用版 perl を買うことができますか？)

=begin original

In a real sense, perl already I<is> commercial software: it has a license
that you can grab and carefully read to your manager. It is distributed
in releases and comes in well-defined packages. There is a very large
user community and an extensive literature.  The comp.lang.perl.*
newsgroups and several of the mailing lists provide free answers to your
questions in near real-time.  Perl has traditionally been supported by
Larry, scores of software designers and developers, and myriad
programmers, all working for free to create a useful thing to make life
better for everyone.

=end original

実際のところ、perl は既に商用ソフトウェアB<です>。
Perl にはあなたがマネージャーの心を捕らえたり、注意深く説明できるような
ライセンスがありますし、Perl は良く定義されたパッケージでリリースされ、
配布されています。
そこには非常に大きなユーザーコミュニティと、広い文化があります。
comp.lang.perl.* ニューズグループと、幾つかのメイリングリストはあなたの
疑問に対してほぼリアルタイムで、無料で回答してくれます。
Perl は伝統的に Larry と、十数人のソフトウェアデザイナーやソフトウェア
開発者、それとたくさんのプログラマーによってサポートされてきました。
すべての作業は無料で、すべての人のためになされました。

=begin original

However, these answers may not suffice for managers who require a
purchase order from a company whom they can sue should anything go awry.
Or maybe they need very serious hand-holding and contractual obligations.
Shrink-wrapped CDs with perl on them are available from several sources if
that will help.  For example, many Perl books include a distribution of perl,
as do the O'Reilly Perl Resource Kits (in both the Unix flavor
and in the proprietary Microsoft flavor); the free Unix distributions
also all come with perl.

=end original

しかし、こういった答えはソフトウェアを購入した会社を、そのソフトウェアに
何か不具合があったときに訴えることができることを要求するようなマネージャーを
満足させるものではないでしょう。
あるいは、彼ら(マネージャー)は、非常に重要な取っかかり(hand-holding)や
契約上の義務を必要としているのかもしれません。
そういったものがある、シュリンクラップされた CD に入った perl が幾つかの
ところから入手できますが、これが助けになるかもしれません。
例えば、多くの Perl 本が Perl の配布キットを同梱しています。
そう、O'Reily の Perl リソースキット (Unix 版と Windows 版があります)が
そうしているように。
フリーな UNIX を配布しているディストリビューターは perl を同梱しています。

=head2 Where do I send bug reports?

(バグレポートはどこへ送るの?)

=begin original

(contributed by brian d foy)

=end original

(brian d foy によって寄贈されました)

=begin original

First, ensure that you've found an actual bug. Second, ensure you've
found an actual bug.

=end original

最初に、本当にバグを発見したことを確認してください。
次に、本当にバグを発見したことを確認してください。

=begin original

If you've found a bug with the perl interpreter or one of the modules
in the standard library (those that come with Perl), you can use the
C<perlbug> utility that comes with Perl (>= 5.004). It collects
information about your installation to include with your message, then
sends the message to the right place.

=end original

perl インタプリタか、(Perl と同梱されている) 標準ライブラリの
モジュールのバグを発見した場合、Perl (>= 5.004) に同梱されている
C<perlbug> ユーティリティが使えます。
これはインストール情報を収集して、あなたのメッセージと共に
適切な場所に送信します。

=begin original

To determine if a module came with your version of Perl, you can
use the C<Module::CoreList> module. It has the information about
the modules (with their versions) included with each release of Perl.

=end original

あるモジュールがあなたが使っている Perl mに同梱されているものかどうかを
決定するためには、C<Module::CoreList> モジュールが使えます。
これは、それぞれの Perl のリリース毎に含まれているモジュール(
およびそのバージョン)に関する情報を保持しています。

=begin original

If C<Module::CoreList> is not installed on your system, check out
http://perlpunks.de/corelist .

=end original

C<Module::CoreList> がインストールされていない場合は、
http://perlpunks.de/corelist を調べてください。

=begin original

Every CPAN module has a bug tracker set up in RT, http://rt.cpan.org .
You can submit bugs to RT either through its web interface or by
email. To email a bug report, send it to
bug-E<lt>distribution-nameE<gt>@rt.cpan.org . For example, if you
wanted to report a bug in C<Business::ISBN>, you could send a message to
bug-Business-ISBN@rt.cpan.org .

=end original

全ての CPAN モジュールには RT ( http://rt.cpan.org ) に設定された
バグトラッカーがあります。
web インターフェースや email を使って RT にバグを送信できます。
バグ報告を email するには、
bug-E<lt>distribution-nameE<gt>@rt.cpan.org に送信してください。
例えば、もし C<Business::ISBN> のバグを報告したい場合は、
メッセージを bug-Business-ISBN@rt.cpan.org に送信します。

=begin original

Some modules might have special reporting requirements, such as a
Sourceforge or Google Code tracking system, so you should check the
module documentation too.

=end original

Sourceforge や Google Code のトラッキングシステムのような、
特別な報告システムがあるモジュールもありますので、
モジュールのドキュメントも確認するべきです。

=head2 What is perl.com? Perl Mongers? pm.org? perl.org? cpan.org?

(perl.com, Perl Mongers, pm.org, perl.org, cpan.org ってなんですか?)

=begin original

Perl.com at http://www.perl.com/ is part of the O'Reilly Network, a
subsidiary of O'Reilly Media.

=end original

http://www.perl.com/ にある Perl.com は O'Reilly Media の子会社である
O'Reilly Network の一部です。

=begin original

The Perl Foundation is an advocacy organization for the Perl language
which maintains the web site http://www.perl.org/ as a general
advocacy site for the Perl language. It uses the domain to provide
general support services to the Perl community, including the hosting
of mailing lists, web sites, and other services.  There are also many
other sub-domains for special topics like learning Perl, Perl news, jobs
in Perl, such as:

=end original

Perl Foundation は Perl 言語の一般的な支援をするための web サイト
http://www.perl.org/ を管理している、Perl 言語の支援団体です。
Perl Foundation は このドメインを、メーリングリストのホスト、
Web サイト、およびその他のサービスを含む Perl コミュニティのための
一般的なサポートサービスを提供するためにドメインを使っています。
Perl の学習、Perl のニュース、Perl での仕事といった特別なトピックのための
多くのサブドメインもあります:

	http://learn.perl.org/
	http://use.perl.org/
	http://jobs.perl.org/
	http://lists.perl.org/

=begin original

Perl Mongers uses the pm.org domain for services related to Perl user
groups, including the hosting of mailing lists and web sites.  See the
Perl user group web site at http://www.pm.org/ for more information about
joining, starting, or requesting services for a Perl user group.

=end original

Perl Mongers は Perl ユーザーグループに関係するサービスのために
pm.org というドメインを使っています。
これにはメーリングリストや web サイトが含まれます。
Perl ユーザーグループへの参加、設立、あるいはサービス要求については
Perl ユーザーグループ web サイト http://www.pm.org/ を参照して下さい。

=begin original

http://www.cpan.org/ is the Comprehensive Perl Archive Network,
a replicated worldwide repository of Perl software, see
the I<What is CPAN?> question earlier in this document.

=end original

http://www.cpan.org/ は the Comprehensive Perl Archive Network と
言って、Perl ソフトウェアの世界的な集積地です。
このドキュメントの最初の方の I<What is CPAN?> を参照して下さい。

=head1 AUTHOR AND COPYRIGHT

Copyright (c) 1997-2010 Tom Christiansen, Nathan Torkington, and
other authors as noted. All rights reserved.

This documentation is free; you can redistribute it and/or modify it
under the same terms as Perl itself.

Irrespective of its distribution, all code examples here are in the public
domain.  You are permitted and encouraged to use this code and any
derivatives thereof in your own programs for fun or for profit as you
see fit.  A simple comment in the code giving credit to the FAQ would
be courteous but is not required.

=begin meta

Translate: 吉村 寿人 <JAE00534@niftyserve.or.jp>
Update: SHIRAKATA Kentaro <argrath@ub32.org> (5.6.1-)
Status: completed

=end meta

