
=encoding euc-jp

=head1 NAME

URI::_punycode - encodes Unicode string in Punycode

=head1 SYNOPSIS

  use URI::_punycode;
  $punycode = encode_punycode($unicode);
  $unicode  = decode_punycode($punycode);

=head1 DESCRIPTION

=begin original

URI::_punycode is a module to encode / decode Unicode strings into
Punycode, an efficient encoding of Unicode for use with IDNA.

=end original

URI::_punycode は、Unicode を、IDNA で使うための Unicode の効率的な
エンコーディングである Punycode との間でエンコード/デコードするための
モジュールです。

=begin original

This module requires Perl 5.6.0 or over to handle UTF8 flagged Unicode
strings.

=end original

このモジュールは、UTF8 フラグを持った Unicode 文字列を扱うために、
Perl 5.6.0 以上が必要です。

=head1 FUNCTIONS

(関数)

=begin original

This module exports following functions by default.

=end original

このモジュールはデフォルトで以下の関数をエクスポートします。

=over 4

=item encode_punycode

  $punycode = encode_punycode($unicode);

=begin original

takes Unicode string (UTF8-flagged variable) and returns Punycode
encoding for it.

=end original

Unicode 文字列 (UTF8 フラグを持った変数) を取り、
Punycode エンコードされたものを返します。

=item decode_punycode

  $unicode = decode_punycode($punycode)

=begin original

takes Punycode encoding and returns original Unicode string.

=end original

Punycode エンコードされたものを取り、
元の Unicode 文字列を返します。

=back

=begin original

These functions throw exceptions on failure. You can catch 'em via
C<eval>.

=end original

これらの関数は失敗時に例外を投げます。
これらは C<eval> で捕捉できます。

=head1 AUTHOR

Tatsuhiko Miyagawa E<lt>miyagawa@bulknews.netE<gt> is the author of
IDNA::Punycode v0.02 which was the basis for this module.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=head1 SEE ALSO

L<IDNA::Punycode>, RFC 3492

=begin meta

Translate: SHIRAKATA Kentaro <argrath@ub32.org> (1.54-)
Status: completed

=end meta

=cut

