
=encoding euc-jp

=head1 名前

Jcode::Unicode::Constants -- UCS2-EUC変換テーブル

=head1 概要

なし

=head1 説明

これにはEUCからUCS2/UCS2からEUCへの変換を行う巨大なハッシュが
入っているだけです。

=head1 参考資料

ftp://ftp.unicode.org/Public/MAPPINGS/EASTASIA/JIS/

Unicodeマッピングデータ

=head1 著作権(COPYRIGHT)

Copyright 1999 Dan Kogai <dankogai@dan.co.jp>

This library is free software; you can redistribute it
and/or modify it under the same terms as Perl itself.

Unicode conversion table here is based on files at 
ftp://ftp.unicode.org/Public/MAPPINGS/EASTASIA/JIS/, 
Copyright (c) 1991-1994 Unicode, Inc.

