=head1 名前

Cache::SizeAwareCacheTester -- サイズをチェックするキャッシュの回帰テストするためのクラス

=head1 説明

SizeCacheTesterは大きさを変更する観点からキャッシュ実装を
確認するために使われます。

=head1 概要

  use Cache::SizeAwareMemoryCache;
  use Cache::SizeAwareCacheTester;

  my $cache = new Cache::SizeAwareMemoryCache( );

  my $cache_tester = new Cache::SizeAwareCacheTester( 1 );

  $cache_tester->test( $cache );

=head1 メソッド

=over

=item B<new( $initial_count )>

カウンタがI<$initial_count>から始まる、
新しいSizeAwareCacheTesterオブジェクトを組み立てます。

=item B<test( )>

テストを実行します。

=back

=head1 参考資料

Cache::Cache, Cache::BaseCacheTester, Cache::CacheTester

=head1 作者

Original author: DeWitt Clinton <dewitt@unto.net>

Last author:     $Author$

Copyright (C) 2001, 2002 DeWitt Clinton

