
=encoding euc-jp

=head1 NAME

=begin original

locale - Perl pragma to use and avoid POSIX locales for built-in operations

=end original

locale - 組み込み演算子で POSIX ロケールを使う/使わないための Perl プラグマ

=head1 SYNOPSIS

    @x = sort @y;	# ASCII sorting order
    {
        use locale;
        @x = sort @y;   # Locale-defined sorting order
    }
    @x = sort @y;	# ASCII sorting order again

=head1 DESCRIPTION

=begin original

This pragma tells the compiler to enable (or disable) the use of POSIX
locales for built-in operations (LC_CTYPE for regular expressions, and
LC_COLLATE for string comparison).  Each "use locale" or "no locale"
affects statements to the end of the enclosing BLOCK.

=end original

このプラグマは、組み込み演算での POSIX ロケール (正規表現では LC_CTYPE、
文字列比較では LC_COLLATE) の仕様を有効(または無効)にすることをコンパイラに
伝えます。
それぞれの "use locale" または "no locale" は、囲んでいる BLOCK の
終わりまでの分に影響します。

=begin original

See L<perllocale> for more detailed information on how Perl supports
locales.

=end original

Perl がどのようにロケールに対応しているかに関するさらに詳細な情報については
L<perllocale> を参照してください。

=cut

