
=encoding utf8

=head1 NAME

=begin original

HTTP::WebTest::Plugin::ResponseTimeTest - Tests for response time

=end original

HTTP::WebTest::Plugin::ResponseTimeTest - 応答時間のテスト

=head1 SYNOPSIS

=begin original

Not Applicable

=end original

なし.

=head1 DESCRIPTION

=begin original

This plugin supports web server response time tests.

=end original

ウェブサーバからの応答時間のテストをできるようになります.

=head1 TEST PARAMETERS

(テストパラメータ)

=head2 min_rtime

=begin original

Minimum web server response time (seconds) expected.

=end original

ウェブサーバからの予期される最小レスポンスタイム(秒).

=head3 Allowed values

(使用可能な値)

=begin original

Any number less than C<max_rtime> (if C<max_rtime> is specified).

=end original

C<max_rtime> より小さい(C<max_rtime> が指定されているとき)整数値.

=head2 max_rtime

=begin original

Maximum web server response time (seconds) expected.

=end original

ウェブサーバからの予期される最大レスポンスタイム(秒).

=head3 Allowed values

(使用可能な値)

=begin original

Any number greater that zero and greater than C<min_rtime> (if
C<min_rtime> is specified).

=end original

0 より大きいかつ C<min_rtime> より大きい(C<min_rtime> が指定
されているとき)整数値.

=head1 COPYRIGHT

Copyright (c) 2000-2001 Richard Anderson.  All rights reserved.


Copyright (c) 2001-2003 Ilya Martynov.  All rights reserved.


=begin original

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=end original

このプログラムはフリーソフトです. このプログラムは Perl 自身と同じ条件下で
再配布・改変可能です.

=head1 SEE ALSO

L<HTTP::WebTest|HTTP::WebTest>


L<HTTP::WebTest::API|HTTP::WebTest::API>


L<HTTP::WebTest::Plugin|HTTP::WebTest::Plugin>


L<HTTP::WebTest::Plugins|HTTP::WebTest::Plugins>


