
=encoding utf8

=head1 NAME

=begin original

HTTP::WebTest::Plugin::StatusTest - Checks the HTTP response status

=end original

HTTP::WebTest::Plugin::StatusTest - HTTP 応答ステータスのチェック

=head1 SYNOPSIS

=begin original

Not Applicable

=end original

なし.

=head1 DESCRIPTION

=begin original

This plugin checks the HTTP response status.

=end original

HTTP 応答ステータスをチェックします.

=head1 TEST PARAMETERS

(テストパラメータ)

=head2 status_code

=begin original

Given numeric HTTP Status Code, tests response returned that value.

=end original

数値で HTTP ステータスコードを与えると, レスポンスで
その値が返されるかをテストします.

=head3 Default value

(デフォルト値)

C<200> (OK).


=head1 COPYRIGHT

Copyright (c) 2000-2001 Richard Anderson.  All rights reserved.


Copyright (c) 2001-2003 Ilya Martynov.  All rights reserved.


=begin original

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=end original

このプログラムはフリーソフトです. このプログラムは Perl 自身と同じ条件下で
再配布・改変可能です.

=head1 SEE ALSO

L<HTTP::WebTest|HTTP::WebTest>


L<HTTP::WebTest::API|HTTP::WebTest::API>


L<HTTP::WebTest::Plugin|HTTP::WebTest::Plugin>


L<HTTP::WebTest::Plugins|HTTP::WebTest::Plugins>


