
=encoding euc-jp

=head1 NAME

=begin original

Net::Server::INET - Net::Server personality

=end original

Net::Server::INET - Net::Serverのパーソナリティ

=head1 概要

  use Net::Server::INET;
  @ISA = qw(Net::Server::INET);

  sub process_request {
     #...コード...
  }

  Net::Server::INET->run();

=head1 説明

=begin original

Please read the pod on Net::Server first.  This module
is a personality, or extension, or sub class, of the
Net::Server module.

=end original

まず始めにNet::ServerのPODを読まれたし。このモジュールは
パーソナリティ(personality)、すなわちNet::Serverの拡張
（サブクラス）である。

=begin original

This personality is intended for use with inetd.  It offers
no methods beyond the Net::Server base class.  This module
operates by overriding the pre_bind, bind, accept, and
post_accept methods to let all socket processing to be done
by inetd.

=end original

このパーソナリティはinetdを使用する。基礎となるNet::Server
クラス以上のメソッドは提供しない。このモジュールはpre_bind、
bind、accept、そしてpost_acceptメソッドをオーバーライドする
ことによって、inetdが行うソケット処理を操作する。

=head1 設定ファイル

=begin original

See L<Net::Server>.

=end original

L<Net::Server>を参照。

=head1 処理の流れ

=begin original

See L<Net::Server>

=end original

L<Net::Server>を参照。

=head1 HOOKS

=begin original

There are no additional hooks in Net::Server::INET.

=end original

Net::Server::INETに追加されるhookはない。

=head1 TO DO

=begin original

See L<Net::Server>

=end original

L<Net::Server>を参照。

=head1 作者

Paul T. Seamons paul@seamons.com

=head1 参考

=begin original

Please see also

=end original

さらに以下も参照して欲しい。

L<Net::Server::Fork>,
L<Net::Server::INET>,
L<Net::Server::PreFork>,
L<Net::Server::MultiType>,
L<Net::Server::Single>

