
=encoding euc-jp

=head1 名前

File::Binary - バイナリ・ファイル読込モジュール

=head1 概要

    use File::Binary qw($BIG_ENDIAN $LITTLE_ENDIAN $NATIVE_ENDIAN);

    my $fb = File::Binary->new("myfile");
    
    $fb->get_ui8();
    $fb->get_ui16();
    $fb->get_ui32();
    $fb->get_si8();
    $fb->get_si16();
    $fb->get_si32();

    $fb->close();

    $fb->open(">newfile");

    $fb->put_ui8(255);
    $fb->put_ui16(65535);
    $fb->put_ui32(4294967295);
    $fb->put_si8(-127);
    $fb->put_si16(-32767);
    $fb->put_si32(-2147483645);
    
    $fb->close();


    $fb->open(IO::Scalar->new($somedata));
    $fb->set_endian($BIG_ENDIAN); # force endianness

    # do what they say on the tin
    $fb->seek($pos);
    $fb->tell();

    # などなど



=head1 依存性

このモジュールは以下のモジュールについて外部依存しています:

 IO::Scalar
 Test::More

=head1 インストール方法

 perl Makefile.PL
 make test

そしてすべてがうまくいったら

 make install

=head1 改変履歴

Perl拡張File::Binaryの改変履歴。

(以下は原文のまま)

1.10  Tue Sep 23 15:43:13 2003
    - add in seek and tell after suggestion from Britton Kerin

1.00  Fri Mar 11 09:28:45 2003
    - finish and uplaod to Cpan

=head1 作者(=AUTHOR)

Copyright 2003, Simon Wistow <simon@thegestalt.org>

=head1 翻訳者

川合 孝典(GCD00051@nifty.ne.jp)

