
=encoding euc-jp

=head1 NAME

=begin original

perl5182delta - what is new for perl v5.18.2

=end original

perl5182delta - perl v5.18.2 での変更点

=head1 DESCRIPTION

=begin original

This document describes differences between the 5.18.1 release and the 5.18.2
release.

=end original

この文書は 5.18.1 リリースと 5.18.2 リリースの変更点を記述しています。

=begin original

If you are upgrading from an earlier release such as 5.18.0, first read
L<perl5181delta>, which describes differences between 5.18.0 and 5.18.1.

=end original

5.18.0 のような以前のリリースから更新する場合は、まず 5.18.0 と
5.18.1 の違いについて記述している L<perl5181delta> を読んでください。

=head1 Modules and Pragmata

(モジュールとプラグマ)

=head2 Updated Modules and Pragmata

(更新されたモジュールとプラグマ)

=over 4

=item *

=begin original

L<B> has been upgraded from version 1.42_01 to 1.42_02.

=end original

L<B> はバージョン 1.42_01 から 1.42_02 に更新されました。

=begin original

The fix for [perl #118525] introduced a regression in the behaviour of
C<B::CV::GV>, changing the return value from a C<B::SPECIAL> object on
a C<NULL> C<CvGV> to C<undef>.  C<B::CV::GV> again returns a
C<B::SPECIAL> object in this case.  [perl #119413]

=end original

[perl #118525] のための修正は、C<B::CV::GV> の振る舞いに対する退行を
導入していて、返り値を C<NULL> C<CvGV> での C<B::SPECIAL> オブジェクトから
C<undef> に変えていました。
C<B::CV::GV> は再びこの場合に C<B::SPECIAL> オブジェクトを
返すようになりました。
[perl #119413]

=item *

=begin original

L<B::Concise> has been upgraded from version 0.95 to 0.95_01.

=end original

L<B::Concise> はバージョン 0.95 から 0.95_01 に更新されました。

=begin original

This fixes a bug in dumping unexpected SEPCIALs.

=end original

これは想定外の SEPCIAL をダンプする場合のバグを修正します。

=item *

=begin original

L<English> has been upgraded from version 1.06 to 1.06_01.  This fixes an
error about the performance of C<$`>, C<$&>, and c<$'>.

=end original

L<English> はバージョン 1.06 から 1.06_01 に更新されました。
これは C<$`>, C<$&>, c<$'> の性能に関する誤りを修正します。

=item *

=begin original

L<File::Glob> has been upgraded from version 1.20 to 1.20_01.

=end original

L<File::Glob> はバージョン 1.20 から 1.20_01 に更新されました。

=back

=head1 Documentation

(文書)

=head2 Changes to Existing Documentation

(既存の文書の変更)

=over 4

=item *

=begin original

L<perlrepository> has been restored with a pointer to more useful pages.

=end original

L<perlrepository> は、より有用なページへのポインタとして復旧されました。

=item *

=begin original

L<perlhack> has been updated with the latest changes from blead.

=end original

L<perlhack> は、blead からの最新の変更に関して更新されました。

=back

=head1 Selected Bug Fixes

(バグ修正の抜粋)

=over 4

=item *

=begin original

Perl 5.18.1 introduced a regression along with a bugfix for lexical subs.
Some B::SPECIAL results from B::CV::GV became undefs instead.  This broke
Devel::Cover among other libraries.  This has been fixed.  [perl #119351]

=end original

Perl 5.18.1 はレキシカルサブルーチンのバグ修正に伴って退行を
導入していました。
B::CV::GV からの一部の B::SPECIAL の結果が代わりに undef になっていました。
これは Devel::Cover などのライブラリを壊していました。
これは修正されました。
[perl #119351]

=item *

=begin original

Perl 5.18.0 introduced a regression whereby C<[:^ascii:]>, if used in the same
character class as other qualifiers, would fail to match characters in the
Latin-1 block.  This has been fixed.  [perl #120799]

=end original

Perl 5.18.0 は C<[:^ascii:]> による退行を導入していて、他の修飾子と同じ
文字クラスとして使われると、Latin-1 ブロックの文字とのマッチングに
失敗していました。
これは修正されました。
[perl #120799]

=item *

=begin original

Perl 5.18.0 introduced a regression when using ->SUPER::method with AUTOLOAD
by looking up AUTOLOAD from the current package, rather than the current
package’s superclass.  This has been fixed. [perl #120694]

=end original

Perl 5.18.0 では、AUTOLOAD つきの ->SUPER::method メソッドが、現在の
パッケージのスーパークラスではなく、現在のパッケージの AUTOLOAD を
探すという退行が導入されていました。
これは修正されました。
[perl #120694]

=item *

=begin original

Perl 5.18.0 introduced a regression whereby C<-bareword> was no longer
permitted under the C<strict> and C<integer> pragmata when used together.  This
has been fixed.  [perl #120288]

=end original

Perl 5.18.0 では、C<strict> と C<integer> プラグマが共に使われて有効な場合に
C<-bareword> がもはや許可されないことによる退行を導入していました。
これは修正されました。
[perl #120288]

=item *

=begin original

Previously PerlIOBase_dup didn't check if pushing the new layer succeeded
before (optionally) setting the utf8 flag. This could cause
segfaults-by-nullpointer.  This has been fixed.

=end original

以前は、PerlIOBase_dup は、(オプションの) utf8 フラグの設定の前に新しい層の
プッシュが成功したかどうかをチェックしていませんでした。
これにより、ヌルポインタによるセグメンテーションフォルトを
引き起こすことがありました。
これは修正されました。

=item *

=begin original

A buffer overflow with very long identifiers has been fixed.

=end original

とても長い識別子によるバッファオーバーフローは修正されました。

=item *

=begin original

A regression from 5.16 in the handling of padranges led to assertion failures
if a keyword plugin declined to handle the second ‘my’, but only after creating
a padop.

=end original

キーワードプラグインが 2 番目の 'my' を padop を作成した後で拒否したときに
padranges の扱いでアサーション失敗を引き起こすという 5.16 からの退行が
ありました。

=begin original

This affected, at least, Devel::CallParser under threaded builds.

=end original

これは、少なくとも、スレッドビルドでの Devel::CallParser に影響を与えます。

=begin original

This has been fixed

=end original

これは修正されました

=item *

=begin original

The construct C<< $r=qr/.../; /$r/p >> is now handled properly, an issue which
had been worsened by changes 5.18.0. [perl #118213]

=end original

5.18.0 の変更によって悪化していた C<< $r=qr/.../; /$r/p >> 構文は正しく
扱われるようになりました。
[perl #118213]

=back

=head1 Acknowledgements

=begin original

Perl 5.18.2 represents approximately 3 months of development since Perl
5.18.1 and contains approximately 980 lines of changes across 39 files from 4
authors.

=end original

Perl 5.18.2 は、Perl 5.18.1 以降、4 人の作者によって、
39 のファイルに約 980 行の変更を加えて、
約 3 months開発されてきました。

=begin original

Perl continues to flourish into its third decade thanks to a vibrant
community of users and developers. The following people are known to have
contributed the improvements that became Perl 5.18.2:

=end original

Perl は、活気のあるユーザーと開発者のコミュニティのおかげで 20 年を超えて
繁栄しています。
以下の人々が、Perl 5.18.2 になるための改良に貢献したことが分かっています:

Craig A. Berry, David Mitchell, Ricardo Signes, Tony Cook.

=begin original

The list above is almost certainly incomplete as it is automatically
generated from version control history. In particular, it does not include
the names of the (very much appreciated) contributors who reported issues to
the Perl bug tracker.

=end original

これはバージョンコントロール履歴から自動的に生成しているので、ほぼ確実に
不完全です。
特に、Perl バグトラッカーに問題を報告をしてくれた (とてもありがたい)貢献者の
名前を含んでいません。

=begin original

Many of the changes included in this version originated in the CPAN modules
included in Perl's core. We're grateful to the entire CPAN community for
helping Perl to flourish.

=end original

このバージョンに含まれている変更の多くは、Perl コアに含まれている CPAN
モジュール由来のものです。
私たちは Perl の発展を助けている CPAN コミュニティ全体に感謝します。

=begin original

For a more complete list of all of Perl's historical contributors, please see
the F<AUTHORS> file in the Perl source distribution.

=end original

全ての Perl の歴史的な貢献者のより完全な一覧については、どうか Perl ソース
配布に含まれている F<AUTHORS> を参照してください。

=head1 Reporting Bugs

(バグ報告)

=begin original

If you find what you think is a bug, you might check the articles recently
posted to the comp.lang.perl.misc newsgroup and the perl bug database at
http://rt.perl.org/perlbug/ .  There may also be information at
http://www.perl.org/ , the Perl Home Page.

=end original

もしバグと思われるものを見つけたら、comp.lang.perl.misc ニュースグループに
最近投稿された記事や http://rt.perl.org/perlbug/ にある perl バグ
データベースを確認してください。
Perl ホームページ、http://www.perl.org/ にも情報があります。

=begin original

If you believe you have an unreported bug, please run the L<perlbug> program
included with your release.  Be sure to trim your bug down to a tiny but
sufficient test case.  Your bug report, along with the output of C<perl -V>,
will be sent off to perlbug@perl.org to be analysed by the Perl porting team.

=end original

もしまだ報告されていないバグだと確信したら、そのリリースに含まれている
L<perlbug> プログラムを実行してください。
バグの再現スクリプトを十分小さく、しかし有効なコードに切りつめることを
意識してください。
バグレポートは C<perl -V> の出力と一緒に perlbug@perl.org に送られ
Perl porting チームによって解析されます。

=begin original

If the bug you are reporting has security implications, which make it
inappropriate to send to a publicly archived mailing list, then please send it
to perl5-security-report@perl.org.  This points to a closed subscription
unarchived mailing list, which includes all the core committers, who will be
able to help assess the impact of issues, figure out a resolution, and help
co-ordinate the release of patches to mitigate or fix the problem across all
platforms on which Perl is supported.  Please only use this address for
security issues in the Perl core, not for modules independently distributed on
CPAN.

=end original

もし報告しようとしているバグがセキュリティに関するもので、公開されている
メーリングリストに送るのが不適切なものなら、
perl5-security-report@perl.org に送ってください。
このアドレスは、問題の影響を評価し、解決法を見つけ、Perl が対応している
全てのプラットフォームで問題を軽減または解決するパッチをリリースするのを
助けることが出来る、全てのコアコミッタが参加している非公開の
メーリングリストになっています。
このアドレスは、独自に CPAN で配布されているモジュールではなく、
Perl コアのセキュリティ問題だけに使ってください。

=head1 SEE ALSO

=begin original

The F<Changes> file for an explanation of how to view exhaustive details on
what changed.

=end original

変更点の完全な詳細を見る方法については F<Changes> ファイル。

=begin original

The F<INSTALL> file for how to build Perl.

=end original

Perl のビルド方法については F<INSTALL> ファイル。

=begin original

The F<README> file for general stuff.

=end original

一般的なことについては F<README> ファイル。

=begin original

The F<Artistic> and F<Copying> files for copyright information.

=end original

著作権情報については F<Artistic> 及び F<Copying> ファイル。

=cut

=begin meta

Translate: SHIRAKATA Kentaro <argrath@ub32.org>
Status: completed

=end meta

