
=encoding utf8

=head1 NAME

=begin original

Getopt::Std - Process single-character switches with switch clustering

=end original

Getopt::Std - スイッチクラスタリング付きの単一文字スイッチ処理

(訳注: (TBR)がついている段落は「みんなの自動翻訳＠TexTra」による
機械翻訳です。)

=head1 SYNOPSIS

    use Getopt::Std;

    getopts('oif:');  # -o & -i are boolean flags, -f takes an argument
		      # Sets $opt_* global variables as a side effect
    getopts('oif:', \my %opts);  # Options as above, values in %opts
    getopt('oDI');    # -o, -D & -I take arguments
                      # Sets $opt_* global variables as a side effect
    getopt('oDI', \my %opts);    # -o, -D & -I take arg, values in %opts

=head1 DESCRIPTION

=begin original

The C<getopts()> function processes single-character switches with switch
clustering.  Pass one argument which is a string containing all switches to be
recognized.  For each switch found, if an argument is expected and provided,
C<getopts()> sets C<$opt_x> (where C<x> is the switch name) to the value of
the argument.  If an argument is expected but none is provided, C<$opt_x> is
set to an undefined value.  If a switch does not take an argument, C<$opt_x>
is set to C<1>.

=end original

C<getopts()>関数は、スイッチクラスタリングを使用して単一文字のスイッチを処理します。
認識されるすべてのスイッチを含む文字列である引数を1つ渡します。
検出されたスイッチごとに、引数が必要で指定されている場合、C<getopts()>はC<$opt_x>(C<x>はスイッチ名)を引数の値に設定します。
引数が必要で指定されていない場合、C<$opt_x>は未定義の値に設定されます。
スイッチが引数を取らない場合、C<$opt_x>はC<1>に設定されます。
(TBR)

=begin original

Switches which take an argument don't care whether there is a space between
the switch and the argument.  If unspecified switches are found on the
command-line, the user will be warned that an unknown option was given.

=end original

引数を取るスイッチは、スイッチと引数の間にスペースがあるかどうかを気にしません。
指定されていないスイッチがコマンドラインで見つかった場合、ユーザは不明なオプションが指定されたことを警告されます。
(TBR)

=begin original

The C<getopts()> function returns true unless an invalid option was found.

=end original

Cの<getopts()>関数は、不正なオプションが見つからなければ真を返します。
(TBR)

=begin original

The C<getopt()> function is similar, but its argument is a string containing
all switches that take an argument.  If no argument is provided for a switch,
say, C<y>, the corresponding C<$opt_y> will be set to an undefined value.
Unspecified switches are silently accepted.  Use of C<getopt()> is B<not
recommended>.

=end original

C<getopt()>関数も似ていますが、引数は引数を取るすべてのスイッチを含む文字列です。
スイッチに引数が指定されていない場合(C<y>など)、対応するC<$opt_y>は未定義の値に設定されます。
指定されていないスイッチは暗黙的に受け入れられます。
C<getopt()>の使用はB<非推奨>です。
(TBR)

=begin original

Note that, if your code is running under the recommended C<use strict
vars> pragma, you will need to declare these package variables
with C<our>:

=end original

コードを推奨されているC<use strict vars>プラグマで実行している場合は、これらのパッケージ変数をC<our>で宣言する必要があることに注意してください。
(TBR)

    our($opt_x, $opt_y);

=begin original

For those of you who don't like additional global variables being created,
C<getopt()> and C<getopts()> will also accept a hash reference as an optional
second argument.  Hash keys will be C<x> (where C<x> is the switch name) with
key values the value of the argument or C<1> if no argument is specified.

=end original

追加のグローバル変数が作成されることを好まない人のために、C<getopt()>とC<getopts()>もオプションの2番目の引数としてハッシュ参照を受け付けます。
ハッシュキーはC<x>(C<x>はスイッチ名)で、キー値は引数の値、引数が指定されていない場合はC<1>です。
(TBR)

=begin original

To allow programs to process arguments that look like switches, but aren't,
both functions will stop processing switches when they see the argument
C<-->.  The C<--> will be removed from C<@ARGV>.

=end original

プログラムがスイッチのように見えるが実際にはそうでない引数を処理できるように、両方の関数は引数C<-->を見つけた時にスイッチの処理を停止します。
C<-->はC<@ARGV>から削除されます。
(TBR)

=head1 C<--help> and C<--version>

=begin original

If C<-> is not a recognized switch letter, C<getopts()> supports arguments
C<--help> and C<--version>.  If C<main::HELP_MESSAGE()> and/or
C<main::VERSION_MESSAGE()> are defined, they are called; the arguments are
the output file handle, the name of option-processing package, its version,
and the switches string.  If the subroutines are not defined, an attempt is
made to generate intelligent messages; for best results, define C<$main::VERSION>.

=end original

C<->が認識可能なスイッチ文字でない場合、C<getopts()>は引数C<--help>とC<--version>をサポートします。
C<main::HELP_MESSAGE()>および/またはC<main::VERSION_MESSAGE()>が定義されている場合、それらが呼び出されます。
引数は、出力ファイルハンドル、オプション処理パッケージの名前、そのバージョン、およびスイッチ文字列です。
サブルーチンが定義されていない場合、インテリジェントメッセージの生成が試行されます。
最良の結果を得るには、C<$main::VERSION>を定義してください。
(TBR)

=begin original

If embedded documentation (in pod format, see L<perlpod>) is detected
in the script, C<--help> will also show how to access the documentation.

=end original

組み込み文書(pod形式、L<perlpod>を参照)がスクリプト内で検出された場合は、C<--help>でも文書へのアクセス方法が表示されます。
(TBR)

=begin original

Note that due to excessive paranoia, if C<$Getopt::Std::STANDARD_HELP_VERSION>
isn't true (the default is false), then the messages are printed on C<STDERR>,
and the processing continues after the messages are printed.  This being
the opposite of the standard-conforming behaviour, it is strongly recommended
to set C<$Getopt::Std::STANDARD_HELP_VERSION> to true.

=end original

過度のパラノイアのため、C<$Getopt::Std::STANDARD_HELP_VERSION>がtrueでない場合(デフォルトはfalse)、メッセージはC<STDERR>に出力され、メッセージが出力された後も処理が続行されます。
これは標準に準拠した動作とは逆であるため、C<$Getopt::Std::STANDARD_HELP_VERSION>をtrueに設定することを強くお勧めします。
(TBR)

=begin original

One can change the output file handle of the messages by setting
C<$Getopt::Std::OUTPUT_HELP_VERSION>.  One can print the messages of C<--help>
(without the C<Usage:> line) and C<--version> by calling functions C<help_mess()>
and C<version_mess()> with the switches string as an argument.

=end original

C<$Getopt::Std::OUTPUT_HELP_VERSION>を設定することで、メッセージの出力ファイルハンドルを変更できます。
引数としてスイッチ文字列を使用して関数C<help_mess()>およびC<version_mess()>を呼び出すことで、C<--help>(C<Usage:>行なし)およびC<--version>のメッセージを出力できます。
(TBR)

=cut

=begin meta

Translate: SHIRAKATA Kentaro <argrath@ub32.org>
Status: in progress

=end meta

