=head1 NAME

RDF::Core - An object oriented Perl modules for handling tasks related to RDF.


=head1 DESCRIPTION

RDF::Core has these parts:

=over 4

=item * B<RDF::Core::Model>

Model provides interface to store RDF statements, ask about them and retrieve them back.

=item * B<RDF::Core::Constants>

Defines usefule constants for the RDF processing like namespaces etc.

=item * B<RDF::Core::Parser>

Generates statements from an RDF XML document.

=item * B<RDF::Core::Model::Parser>

Model::Parser is a simple interface object to a parser. It's purpose is to provide a prototype of object accomodating any other parser.

=item * B<RDF::Core::Serializer>

Serializes RDF Model into XML.

=item * B<RDF::Core::Model::Serializer>

Model::Serializer is an interface object for Serializer.

=item * B<RDF::Core::Storage>

An object for storing statements. There are several implementations of Storage - in memory, in a BerkeleyDB 1.x (DB_File) files and PostgreSQL database.

=item * B<RDF::Core::Enumerator>

Enumerator is a result set of statements retrieved from Model

=item * B<RDF::Core::Query>

An implementation of query language.

=item * B<RDF::Core::Schema>

The RDF Schema utilities.

=item * B<Basic elements>

RDF::Core::Statement, RDF::Core::Resource, RDF::Core::Literal, RDF::Core::Node

=back

=head1 LICENSE

This package is subject to the MPL (or the GPL alternatively).

=head1 AUTHOR

Ginger Alliance, rdf@gingerall.cz

=head1 SEE ALSO

perl(1).


=cut

