=head1 名前

Net::Domain - 現在のホストのインターネット名とドメインを評価しようとします

=head1 概要

    use Net::Domain qw(hostname hostfqdn hostdomain);

=head1 説明

さまざまなメソッドを使うことは、現在のホストの
完全修飾ドメイン名(=Fully Qualified Domain Name) (FQDN)を見つけようとB<試みます>。
これにより、ホスト名とホスト・ドメイン名を判定します。

それぞれの関数はFQDNを判定できなければ、I<undef>を返します。

=over 4

=item hostfqdn ()

現在のホストのFQDNをを識別し返します。

=item hostname ()

ホストを識別するために使うことができるFQDNの最も小さい部分を返します。

=item hostdomain ()

I<hostname>が削除された後のFQDNでの残りの部分を返します。

=back

=head1 作者

Graham Barr <gbarr@pobox.com>.
Adapted from Sys::Hostname by David Sundstrom <sunds@asictest.sc.ti.com>

=head1 著作権(COPYRIGHT)

Copyright (c) 1995-1998 Graham Barr. All rights reserved.
This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=for html <hr>

I<$Id$>

