=head1 名前

AnyData::Format::Paragraph - 垂直なファイルへのtieされたハッシュとDBIによるアクセス

=head1 概要

 use AnyData;
 my $table = adHash( 'Paragraph', $filename,'r',$flags );
 while (my $row = each %$table) {
    print $row->{name},"\n" if $row->{country} =~ /us|mx|ca/;
 }
 # ... その他のtieされたハッシュの操作

 または

 use DBI
 my $dbh = DBI->connect('dbi:AnyData:');
 $dbh->func('table1','Paragraph', $filename,$flags,'ad_catalog');
 my $hits = $dbh->selectall_arrayref( qq{
     SELECT name FROM table1 WHERE country = 'us'
 });
 # ... その他のDBI/SQL操作

=head1 説明

これはAnyDataとDBD::AnyDataモジュールのためのプラグイン・フォーマット・パーサーです。

これはレコード名の行から始まり、その後ろにレコードが続くような、"垂直な"ファイルを扱います。 
例えば

 Photoslop
 /My Photos/
 .jpg, .gif, .psd

 Nutscrape
 /htdocs/
 .html, .htm

さらなる詳細はAnyData.pmとDBD::AnyData.pmのドキュメントをご覧ください。 

=head1 作者と著作権(=AUTHOR & COPYRIGHT)

copyright 2000, Jeff Zucker <jeff@vpservices.com>
all rights reserved

=head1 翻訳者

川合孝典(GCD00051@nifty.ne.jp)

