
=encoding euc-jp

=head1 名前

CGI::Util - CGIモジュールによって使われる内部ユーティリティ

=head1 概要

なし

=head1 説明

パブリックなサブルーチンはありません。

=head1 作者情報(AUTHOR INFORMATION)

Copyright 1995-1998, Lincoln D. Stein.  All rights reserved.  

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

バグレポートとコメントはこちらへ: lstein@cshl.org。バグレポートを
送るときには、あなたが使っているCGI.pmのバージョン、Perlのバージョン、
Webサーバーの名前とバージョン、オペレーティング・システムの名前と
バージョンを教えてください。問題がリモートのブラウザに依存する
場合には、影響を与えるブラウザについての情報もお願いします。

=head1 参考資料

L<CGI>

=head1 翻訳者

川合孝典(GCD00051@nifty.ne.jp)

