=encoding utf8

=head1 NAME

=begin original

perlbot - Links to information on object-oriented programming in Perl

=end

perlbot - Perlのオブジェクト指向プログラミングに関する情報へのリンク

=head1 DESCRIPTION

=begin original

For information on OO programming with Perl, please see L<perlootut>
and L<perlobj>.

=end

Perlのオブジェクト指向プログラミングに関する情報は、L<perlootut>
とL<perlobj>を見てください。

=begin original

(The above documents supersede the collection of tricks that was formerly here
in perlbot.)

=end

(上記は、以前perlbotにあったチュートリアルに代わるドキュメント
になります)

=cut

