
=encoding euc-jp

=head1 NAME

=begin original

perldelta - what is new for perl v5.20.1

=end original

perl5201delta - perl v5.20.1 での変更点

=head1 DESCRIPTION

=begin original

This document describes differences between the 5.20.0 release and the 5.20.1
release.

=end original

この文書は 5.20.0 リリースと 5.20.1 リリースの変更点を記述しています。

=begin original

If you are upgrading from an earlier release such as 5.18.0, first read
L<perl5200delta>, which describes differences between 5.18.0 and 5.20.0.

=end original

5.18.0 のような以前のリリースから更新する場合は、まず 5.18.0 と
5.20.0 の違いについて記述している L<perl5200delta> を読んでください。

=head1 Incompatible Changes

(互換性のない変更)

=begin original

There are no changes intentionally incompatible with 5.20.0.  If any exist,
they are bugs, and we request that you submit a report.  See L</Reporting Bugs>
below.

=end original

故意に、5.20.0 から互換性がなくなるようにした変更はありません。
もし 5.20.0 との互換性がなければ、それはバグですので、報告をお願いします。
以下の L</Reporting Bugs> を参照してください。

=head1 Performance Enhancements

(性能改善)

=over 4

=item *

=begin original

An optimization to avoid problems with COW and deliberately overallocated PVs
has been disabled because it interfered with another, more important,
optimization, causing a slowdown on some platforms.
L<[perl #121975]|https://rt.perl.org/Ticket/Display.html?id=121975>

=end original

COW と、意図的に余分に割り当てた PV の問題を避けるための最適化は
無効化されました; これは、より重要な他の最適化を妨げ、一部のプラットフォームで
遅くなっていたからです。
L<[perl #121975]|https://rt.perl.org/Ticket/Display.html?id=121975>

=item *

=begin original

Returning a string from a lexical variable could be slow in some cases.  This
has now been fixed.
L<[perl #121977]|https://rt.perl.org/Ticket/Display.html?id=121977>

=end original

レキシカル変数から文字列を返すのは一部の場合で遅くなっていました。
これは修正されました。
L<[perl #121977]|https://rt.perl.org/Ticket/Display.html?id=121977>

=back

=head1 Modules and Pragmata

(モジュールとプラグマ)

=head2 Updated Modules and Pragmata

(更新されたモジュールとプラグマ)

=over 4

=item *

=begin original

L<Config::Perl::V> has been upgraded from version 0.20 to 0.22.

=end original

L<Config::Perl::V> はバージョン 0.20 から 0.22 に更新されました。

=begin original

The list of Perl versions covered has been updated and some flaws in the
parsing have been fixed.

=end original

対応する Perl のバージョンの一覧が更新され、パース時の問題が修正されました。

=item *

=begin original

L<Exporter> has been upgraded from version 5.70 to 5.71.

=end original

L<Exporter> はバージョン 5.70 から 5.71 に更新されました。

=begin original

Illegal POD syntax in the documentation has been corrected.

=end original

文書の不正な POD 文法が修正されました。

=item *

=begin original

L<ExtUtils::CBuilder> has been upgraded from version 0.280216 to 0.280217.

=end original

L<ExtUtils::CBuilder> はバージョン 0.280216 から 0.280217 に更新されました。

=begin original

Android builds now link to both B<-lperl> and C<$Config::Config{perllibs}>.

=end original

Android ビルドは B<-lperl> と C<$Config::Config{perllibs}> の両方を
リンクするようになりました。

=item *

=begin original

L<File::Copy> has been upgraded from version 2.29 to 2.30.

=end original

L<File::Copy> はバージョン 2.29 から 2.30 に更新されました。

=begin original

The documentation now notes that C<copy> will not overwrite read-only files.

=end original

C<copy> は読み込み専用ファイルを上書きしないことが文書に記述されました。

=item *

=begin original

L<Module::CoreList> has been upgraded from version 3.11 to 5.020001.

=end original

L<Module::CoreList> はバージョン 3.11 から 5.020001 に更新されました。

=begin original

The list of Perl versions covered has been updated.

=end original

対応する Perl バージョンの一覧が更新されました。

=item *

=begin original

The PathTools module collection has been upgraded from version 3.47 to 3.48.

=end original

collection はバージョン 3.47 から 3.48 に更新されました。

=begin original

Fallbacks are now in place when cross-compiling for Android and
C<$Config::Config{sh}> is not yet defined.
L<[perl #121963]|https://rt.perl.org/Ticket/Display.html?id=121963>

=end original

Android のためにクロスコンパイルして、C<$Config::Config{sh}> がまだ
定義されていなかったとき、適切な場所にフォールバックするようになりました。
L<[perl #121963]|https://rt.perl.org/Ticket/Display.html?id=121963>

=item *

=begin original

L<PerlIO::via> has been upgraded from version 0.14 to 0.15.

=end original

L<PerlIO::via> はバージョン 0.14 から 0.15 に更新されました。

=begin original

A minor portability improvement has been made to the XS implementation.

=end original

XS 実装に小さな移植性の向上が行われました。

=item *

=begin original

L<Unicode::UCD> has been upgraded from version 0.57 to 0.58.

=end original

L<Unicode::UCD> はバージョン 0.57 から 0.58 に更新されました。

=begin original

The documentation includes many clarifications and fixes.

=end original

文書は多くの明確化と修正が行われました。

=item *

=begin original

L<utf8> has been upgraded from version 1.13 to 1.13_01.

=end original

L<utf8> はバージョン 1.13 から 1.13_01 に更新されました。

=begin original

The documentation has some minor formatting improvements.

=end original

文書は小さなフォーマットの向上が行われました。

=item *

=begin original

L<version> has been upgraded from version 0.9908 to 0.9909.

=end original

L<version> はバージョン 0.9908 から 0.9909 に更新されました。

=begin original

External libraries and Perl may have different ideas of what the locale is.
This is problematic when parsing version strings if the locale's numeric
separator has been changed.  Version parsing has been patched to ensure it
handles the locales correctly.
L<[perl #121930]|https://rt.perl.org/Ticket/Display.html?id=121930>

=end original

外部ライブラリと Perl は、ロケールとは何かについて異なった考えを持っています。
これは、ロケールの数値セパレータが変更されるとバージョン文字列を
パースするときに問題になります。
バージョンのパースは、ロケールを正しく扱えるようにパッチが当てられました。
L<[perl #121930]|https://rt.perl.org/Ticket/Display.html?id=121930>

=back

=head1 Documentation

(文書)

=head2 Changes to Existing Documentation

(既存の文書の変更)

=head3 L<perlapi>

=over 4

=item *

=begin original

C<av_len> - Emphasize that this returns the highest index in the array, not the
size of the array.
L<[perl #120386]|https://rt.perl.org/Ticket/Display.html?id=120386>

=end original

C<av_len> - これは配列のサイズではなく、配列の最大のインデックスを
返すということが強調されました。
L<[perl #120386]|https://rt.perl.org/Ticket/Display.html?id=120386>

=item *

=begin original

Note that C<SvSetSV> doesn't do set magic.

=end original

C<SvSetSV> は set magic を行わないことが記述されました。

=item *

=begin original

C<sv_usepvn_flags> - Fix documentation to mention the use of C<NewX> instead of
C<malloc>.
L<[perl #121869]|https://rt.perl.org/Ticket/Display.html?id=121869>

=end original

C<sv_usepvn_flags> - C<malloc> ではなく C<NewX> を使うことを言及するように
文書が修正されました。
L<[perl #121869]|https://rt.perl.org/Ticket/Display.html?id=121869>

=item *

=begin original

Clarify where C<NUL> may be embedded or is required to terminate a string.

=end original

どこで C<NUL> は組み込みかも知れず、文字列を終端するのに必要であるかが
明確化されました。

=back

=head3 L<perlfunc>

=over 4

=item *

=begin original

Clarify the meaning of C<-B> and C<-T>.

=end original

C<-B> と C<-T> の意味が明確化されました。

=item *

=begin original

C<-l> now notes that it will return false if symlinks aren't supported by the
file system.
L<[perl #121523]|https://rt.perl.org/Ticket/Display.html?id=121523>

=end original

C<-l> は、シンボリックリンクがファイルシステムで対応していないと偽を返すことが
記述されました。
L<[perl #121523]|https://rt.perl.org/Ticket/Display.html?id=121523>

=item *

=begin original

Note that C<each>, C<keys> and C<values> may produce different orderings for
tied hashes compared to other perl hashes.
L<[perl #121404]|https://rt.perl.org/Ticket/Display.html?id=121404>

=end original

C<each>, C<keys>, C<values> は、他の perl ハッシュと比較して、tie された
ハッシュで異なった順序を出力することが記述されました。
L<[perl #121404]|https://rt.perl.org/Ticket/Display.html?id=121404>

=item *

=begin original

Note that C<exec LIST> and C<system LIST> may fall back to the shell on Win32.
Only C<exec PROGRAM LIST> and C<system PROGRAM LIST> indirect object syntax
will reliably avoid using the shell.  This has also been noted in L<perlport>.
L<[perl #122046]|https://rt.perl.org/Ticket/Display.html?id=122046>

=end original

C<exec LIST> と C<system LIST> は Win32 ではシェルに
フォールバックするかも知れないことが記述されました。
C<exec PROGRAM LIST> と C<system PROGRAM LIST> の間接オブジェクト構文のみが
確実にシェルの使用を避けられます。
これは L<perlport> にも記述されました。
L<[perl #122046]|https://rt.perl.org/Ticket/Display.html?id=122046>

=item *

=begin original

Clarify the meaning of C<our>.
L<[perl #122132]|https://rt.perl.org/Ticket/Display.html?id=122132>

=end original

C<our> の意味が明確化されました。
L<[perl #122132]|https://rt.perl.org/Ticket/Display.html?id=122132>

=back

=head3 L<perlguts>

=over 4

=item *

=begin original

Explain various ways of modifying an existing SV's buffer.
L<[perl #116925]|https://rt.perl.org/Ticket/Display.html?id=116925>

=end original

既にある SV バッファを変更する様々な方法が説明されました。
L<[perl #116925]|https://rt.perl.org/Ticket/Display.html?id=116925>

=back

=head3 L<perlpolicy>

=over 4

=item *

=begin original

We now have a code of conduct for the I<< p5p >> mailing list, as documented in
L<< perlpolicy/STANDARDS OF CONDUCT >>.

=end original

I<< p5p >> メーリングリストに関する行動規範が
L<< perlpolicy/STANDARDS OF CONDUCT >> に文書化されました。

=back

=head3 L<perlre>

=over 4

=item *

=begin original

The C</x> modifier has been clarified to note that comments cannot be continued
onto the next line by escaping them.

=end original

C</x> 修飾子は、エスケープすることでコメントが次の行に引き続かないことが
明確化されました。

=back

=head3 L<perlsyn>

=over 4

=item *

=begin original

Mention the use of empty conditionals in C<for>/C<while> loops for infinite
loops.

=end original

無限ループのための条件なしの C<for>/C<while> の使用法が言及されました。

=back

=head3 L<perlxs>

=over 4

=item *

=begin original

Added a discussion of locale issues in XS code.

=end original

XS コードでのロケール問題の議論が追加されました。

=back

=head1 Diagnostics

(診断メッセージ)

=begin original

The following additions or changes have been made to diagnostic output,
including warnings and fatal error messages.  For the complete list of
diagnostic messages, see L<perldiag>.

=end original

以下の追加や変更が、警告や致命的エラーメッセージ含む診断出力に行われました。
完全な診断メッセージの一覧については、L<perldiag> を参照してください。

=head2 Changes to Existing Diagnostics

(既存の診断メッセージの変更)

=over 4

=item *

L<Variable length lookbehind not implemented in regex mE<sol>%sE<sol>|perldiag/"Variable length lookbehind not implemented in regex m/%s/">

=begin original

Information about Unicode behaviour has been added.

=end original

Unicode の振る舞いに関する情報が追加されました。

=back

=head1 Configuration and Compilation

(設定とコンパイル)

=over 4

=item *

=begin original

Building Perl no longer writes to the source tree when configured with
F<Configure>'s B<-Dmksymlinks> option.
L<[perl #121585]|https://rt.perl.org/Ticket/Display.html?id=121585>

=end original

F<Configure> の B<-Dmksymlinks> オプションが指定されたとき、Perl のビルドは
もはやソースツリーに書き込まなくなりました。
L<[perl #121585]|https://rt.perl.org/Ticket/Display.html?id=121585>

=back

=head1 Platform Support

(プラットフォーム対応)

=head2 Platform-Specific Notes

(プラットフォーム固有の注意)

=over 4

=item Android

=begin original

Build support has been improved for cross-compiling in general and for Android
in particular.

=end original

一般的に、そして特に Android 用に、クロスコンパイルでのビルド対応が
改良されました。

=item OpenBSD

=begin original

Corrected architectures and version numbers used in configuration hints when
building Perl.

=end original

Perl をビルドするときの設定ヒントで使われるアーキテクチャとバージョン番号が
修正されました。

=item Solaris

=begin original

B<c99> options have been cleaned up, hints look for B<solstudio> as well as
B<SUNWspro>, and support for native C<setenv> has been added.

=end original

B<c99> オプションは整理され、ヒントは B<SUNWspro> 同様 B<solstudio> も
探すようになり、ネイティブな C<setenv> のための対応が追加されました。

=item VMS

=begin original

An old bug in feature checking, mainly affecting pre-7.3 systems, has been
fixed.

=end original

主に 7.3 より前のシステムに影響するような、機能チェックに関する古いバグが
修正されました。

=item Windows

=begin original

C<%I64d> is now being used instead of C<%lld> for MinGW.

=end original

MinGW では C<%lld> ではなく C<%I64d> を使うようになりました。

=back

=head1 Internal Changes

(内部の変更)

=over 4

=item *

=begin original

Added L<perlapi/sync_locale>.
Changing the program's locale should be avoided by XS code.  Nevertheless,
certain non-Perl libraries called from XS, such as C<Gtk> do so.  When this
happens, Perl needs to be told that the locale has changed.  Use this function
to do so, before returning to Perl.

=end original

L<perlapi/sync_locale> が追加されました。
XS コードでプログラムのロケールを変更することは避けるべきです。
それでも、C<Gtk> のような、XS から呼び出される一部の非 Perl ライブラリは
それをします。
これが起きると、Perl はロケールが変更されたことを知らされる必要があります。
この関数は、Perl に戻る前にそれを行います。

=back

=head1 Selected Bug Fixes

(バグ修正の抜粋)

=over 4

=item *

=begin original

A bug has been fixed where zero-length assertions and code blocks inside of a
regex could cause C<pos> to see an incorrect value.
L<[perl #122460]|https://rt.perl.org/Ticket/Display.html?id=122460>

=end original

正規表現の中のゼロ幅表明とコードブロックで C<pos> が間違った値を見るバグが
修正されました。
L<[perl #122460]|https://rt.perl.org/Ticket/Display.html?id=122460>

=item *

=begin original

Using C<s///e> on tainted utf8 strings could issue bogus "Malformed UTF-8
character (unexpected end of string)" warnings.  This has now been fixed.
L<[perl #122148]|https://rt.perl.org/Ticket/Display.html?id=122148>

=end original

汚染された utf8 文字列に対して C<s///e> を使うと、"Malformed UTF-8
character (unexpected end of string)" 警告を出すことがありました。
これは修正されました。
L<[perl #122148]|https://rt.perl.org/Ticket/Display.html?id=122148>

=item *

=begin original

C<system> and friends should now work properly on more Android builds.

=end original

C<system> 及びその同類は、より多くの Android ビルドで適切に
動作するようになりました。

=begin original

Due to an oversight, the value specified through B<-Dtargetsh> to F<Configure>
would end up being ignored by some of the build process.  This caused perls
cross-compiled for Android to end up with defective versions of C<system>,
C<exec> and backticks: the commands would end up looking for F</bin/sh> instead
of F</system/bin/sh>, and so would fail for the vast majority of devices,
leaving C<$!> as C<ENOENT>.

=end original

見落としによって、B<-Dtargetsh> によって F<Configure> に指定された値は
一部のビルドプロセスでは無視されることになっていました。
これにより、Android のためにクロスコンパイルされた perl は C<system>, C<exec>,
逆クォートに欠陥のあるバージョンになっていました: コマンドは
F</system/bin/sh> ではなく F</bin/sh> を探し、デバイスの圧倒的多数では
失敗して、C<$!> に C<ENOENT> を設定していました。

=item *

=begin original

Many issues have been detected by L<Coverity|http://www.coverity.com/> and 
fixed.

=end original

L<Coverity|http://www.coverity.com/> によって検出された多くの問題が
修正されました。

=back

=head1 Acknowledgements

=begin original

Perl 5.20.1 represents approximately 4 months of development since Perl 5.20.0
and contains approximately 12,000 lines of changes across 170 files from 36
authors.

=end original

Perl 5.20.1 は、Perl 5.20.0 以降、36 人の作者によって、
170 のファイルに約 12,000 行の変更を加えて、
約 4 months開発されてきました。

=begin original

Excluding auto-generated files, documentation and release tools, there were
approximately 2,600 lines of changes to 110 .pm, .t, .c and .h files.

=end original

自動生成ファイル、文書、リリースツールを除くと、110 の .pm, .t, .c,
.h ファイルに約 2,600 行の変更を加えました。

=begin original

Perl continues to flourish into its third decade thanks to a vibrant community
of users and developers.  The following people are known to have contributed
the improvements that became Perl 5.20.1:

=end original

Perl は、活気のあるユーザーと開発者のコミュニティのおかげで 20 年を超えて
繁栄しています。
以下の人々が、Perl 5.20.1 になるための改良に貢献したことが分かっています:

Aaron Crane, Abigail, Alberto SimE<otilde>es, Alexandr Ciornii, Alexandre (Midnite)
Jousset, Andrew Fresh, Andy Dougherty, Brian Fraser, Chris 'BinGOs' Williams,
Craig A. Berry, Daniel Dragan, David Golden, David Mitchell, H.Merijn Brand,
James E Keenan, Jan Dubois, Jarkko Hietaniemi, John Peacock, kafka, Karen
Etheridge, Karl Williamson, Lukas Mai, Matthew Horsfall, Michael Bunk, Peter
Martini, Rafael Garcia-Suarez, Reini Urban, Ricardo Signes, Shirakata Kentaro,
Smylers, Steve Hay, Thomas Sibley, Todd Rinaldo, Tony Cook, Vladimir Marek,
Yves Orton.

=begin original

The list above is almost certainly incomplete as it is automatically generated
from version control history.  In particular, it does not include the names of
the (very much appreciated) contributors who reported issues to the Perl bug
tracker.

=end original

これはバージョンコントロール履歴から自動的に生成しているので、ほぼ確実に
不完全です。
特に、Perl バグトラッカーに問題を報告をしてくれた (とてもありがたい)貢献者の
名前を含んでいません。

=begin original

Many of the changes included in this version originated in the CPAN modules
included in Perl's core.  We're grateful to the entire CPAN community for
helping Perl to flourish.

=end original

このバージョンに含まれている変更の多くは、Perl コアに含まれている CPAN
モジュール由来のものです。
私たちは Perl の発展を助けている CPAN コミュニティ全体に感謝します。

=begin original

For a more complete list of all of Perl's historical contributors, please see
the F<AUTHORS> file in the Perl source distribution.

=end original

全ての Perl の歴史的な貢献者のより完全な一覧については、どうか Perl ソース
配布に含まれている F<AUTHORS> を参照してください。

=head1 Reporting Bugs

(バグ報告)

=begin original

If you find what you think is a bug, you might check the articles recently
posted to the comp.lang.perl.misc newsgroup and the perl bug database at
https://rt.perl.org/ .  There may also be information at http://www.perl.org/ ,
the Perl Home Page.

=end original

もしバグと思われるものを見つけたら、comp.lang.perl.misc ニュースグループに
最近投稿された記事や http://rt.perl.org/perlbug/ にある perl バグ
データベースを確認してください。
Perl ホームページ、http://www.perl.org/ にも情報があります。

=begin original

If you believe you have an unreported bug, please run the L<perlbug> program
included with your release.  Be sure to trim your bug down to a tiny but
sufficient test case.  Your bug report, along with the output of C<perl -V>,
will be sent off to perlbug@perl.org to be analysed by the Perl porting team.

=end original

もしまだ報告されていないバグだと確信したら、そのリリースに含まれている
L<perlbug> プログラムを実行してください。
バグの再現スクリプトを十分小さく、しかし有効なコードに切りつめることを
意識してください。
バグレポートは C<perl -V> の出力と一緒に perlbug@perl.org に送られ
Perl porting チームによって解析されます。

=begin original

If the bug you are reporting has security implications, which make it
inappropriate to send to a publicly archived mailing list, then please send it
to perl5-security-report@perl.org.  This points to a closed subscription
unarchived mailing list, which includes all the core committers, who will be
able to help assess the impact of issues, figure out a resolution, and help
co-ordinate the release of patches to mitigate or fix the problem across all
platforms on which Perl is supported.  Please only use this address for
security issues in the Perl core, not for modules independently distributed on
CPAN.

=end original

もし報告しようとしているバグがセキュリティに関するもので、公開されている
メーリングリストに送るのが不適切なものなら、
perl5-security-report@perl.org に送ってください。
このアドレスは、問題の影響を評価し、解決法を見つけ、Perl が対応している
全てのプラットフォームで問題を軽減または解決するパッチをリリースするのを
助けることが出来る、全てのコアコミッタが参加している非公開の
メーリングリストになっています。
このアドレスは、独自に CPAN で配布されているモジュールではなく、
Perl コアのセキュリティ問題だけに使ってください。

=head1 SEE ALSO

=begin original

The F<Changes> file for an explanation of how to view exhaustive details on
what changed.

=end original

変更点の完全な詳細を見る方法については F<Changes> ファイル。

=begin original

The F<INSTALL> file for how to build Perl.

=end original

Perl のビルド方法については F<INSTALL> ファイル。

=begin original

The F<README> file for general stuff.

=end original

一般的なことについては F<README> ファイル。

=begin original

The F<Artistic> and F<Copying> files for copyright information.

=end original

著作権情報については F<Artistic> 及び F<Copying> ファイル。

=cut

=begin meta

Translate: SHIRAKATA Kentaro <argrath@ub32.org>
Status: completed

=end meta

