
=encoding utf8

=head1 NAME

=begin original

perlbook - Books about and related to Perl

=end original

perlbook - Perl およびそれに関連する本

=head1 DESCRIPTION

=begin original

There are many books on Perl and Perl-related. A few of these are
good, some are OK, but many aren't worth your money. There is a list
of these books, some with extensive reviews, at
L<https://www.perl.org/books/library.html> . We list some of the books here, and while
listing a book implies our
endorsement, don't think that not including a book means anything.

=end original

Perl および Perl に関する多くの本があります。
それらの二、三はいいもので、いくつかはまあまあですが、多くのものはお金を
払う価値はありません。
これらの本に関して、一部は大規模なレビュー付きで、一覧が
L<https://www.perl.org/books/library.html> にあります。
ここにそれらの本の一部を載せ、挙げられた本を推薦していることを
暗示していますが、ここに含まれていない本に意味がないとは考えないでください。

=begin original

Most of these books are available online through O'Reilly Online Learning
( L<https://www.oreilly.com> ).

=end original

これらの本のほとんどは O'Reilly Online Learning
( L<https://www.oreilly.com> ) 経由でオンラインで利用可能です。

=head2 The most popular books

(最も有名な本)

=begin original

The major reference book on Perl, written by the creator of Perl, is
I<Programming Perl>:

=end original

Perl の創造者によって書かれた重要な Perl に関するリファレンス本は、
I<Programming Perl> です:

=over 4

=item I<Programming Perl> (the "Camel Book"):

(I<プログラミング Perl>(ラクダ本))

=begin original

 by Tom Christiansen, brian d foy, Larry Wall with Jon Orwant
 ISBN 978-0-596-00492-7 [4th edition February 2012]
 ISBN 978-1-4493-9890-3 [ebook]
 https://www.oreilly.com/library/view/-/9781449321451/

=end original

 by Tom Christiansen, brian d foy, Larry Wall with Jon Orwant
 ISBN 978-0-596-00492-7 [4th edition February 2012]
 ISBN 978-1-4493-9890-3 [ebook]
 https://www.oreilly.com/library/view/-/9781449321451/
 ISBN 4873110963     (第 3 版日本語版第 1 巻)
 https://www.oreilly.co.jp/books/4873110963/
 ISBN 4873110971     (第 3 版日本語版第 2 巻)
 https://www.oreilly.co.jp/books/4873110971/

=back

=begin original

The Ram is a cookbook with hundreds of examples of using Perl to
accomplish specific tasks:

=end original

ラム本は特定の作業を達成するために Perl を使うためのたくさんの例が載っている
クックブックです:

=over 4

=item I<The Perl Cookbook> (the "Ram Book"):

(I<Perl クックブック>:)

=begin original

 by Tom Christiansen and Nathan Torkington,
 with Foreword by Larry Wall
 ISBN 978-0-596-00313-5 [2nd Edition August 2003]
 ISBN 978-0-596-15888-0 [ebook]
 https://www.oreilly.com/library/view/-/0596003137/

=end original

 by Tom Christiansen and Nathan Torkington,
 with Foreword by Larry Wall
 ISBN 978-0-596-00313-5 [2nd Edition August 2003]
 ISBN 978-0-596-15888-0 [ebook]
 https://www.oreilly.com/library/view/-/0596003137/
 ISBN 4-87311-202-8 (日本語版第 1 巻)
 https://www.oreilly.co.jp/books/4873112028/
 ISBN 4-87311-203-6 (日本語版第 2 巻)
 https://www.oreilly.co.jp/books/4873112036/

=back

=begin original

If you want to learn the basics of Perl, you might start with the
Llama book, which assumes that you already know a little about
programming:

=end original

Perl の基本を学びたいなら、リャマ本から始めると良いかもしれません; これは
あなたがプログラミング自体については既に少し知っていると仮定しています:

=over 4

=item I<Learning Perl>  (the "Llama Book")

(I<初めての Perl> (リャマ本))

=begin original

 by Randal L. Schwartz, Tom Phoenix, and brian d foy
 ISBN 978-1-4920-9495-1 [8th edition August 2021]
 ISBN 978-1-4920-9492-0 [ebook]
 https://www.learning-perl.com/

=end original

 by Randal L. Schwartz, Tom Phoenix, and brian d foy
 ISBN 978-1-4920-9495-1 [8th edition August 2021]
 ISBN 978-1-4920-9492-0 [ebook]
 https://www.learning-perl.com/
 ISBN 978-4-87311-824-6 (第 7 版日本語版)
 https://www.oreilly.co.jp/books/9784873118246/

=back

=begin original

The tutorial started in the Llama continues in the Alpaca, which
introduces the intermediate features of references, data structures,
object-oriented programming, and modules:

=end original

リャマ本で始まったチュートリアルはアルパカ本に続いていて、リファレンス、
データ構造、オブジェクト指向プログラミング、モジュールといった中級の
機能を説明しています:

=over 4

=item I<Intermediate Perl> (the "Alpaca Book")

(I<続・初めての Perl 改訂版> (アルパカ本))

=begin original

 by Randal L. Schwartz and brian d foy, with Tom Phoenix
         foreword by Damian Conway
 ISBN 978-1-4493-9309-0 [2nd edition August 2012]
 ISBN 978-1-4493-0459-1 [ebook]
 https://www.intermediateperl.com/

=end original

 by Randal L. Schwartz and brian d foy, with Tom Phoenix
         foreword by Damian Conway
 ISBN 978-1-4493-9309-0 [2nd edition August 2012]
 ISBN 978-1-4493-0459-1 [ebook]
 https://www.intermediateperl.com/
 ISBN 978-4-87311-628-0 (日本語版)
 https://www.oreilly.co.jp/books/9784873116280/

=back

=head2 References

=begin original

You might want to keep these desktop references close by your keyboard:

=end original

次のようなデスクトップリファレンスをキーボードのそばに
置いておくのもよいでしょう:

=over 4

=item I<Perl 5 Pocket Reference>

(I<Perl5 デスクトップリファレンス>)

=begin original

 by Johan Vromans
 ISBN 978-1-4493-0370-9 [5th edition July 2011]
 ISBN 978-1-4493-0813-1 [ebook]
 https://www.oreilly.com/library/view/-/9781449311186/

=end original

 by Johan Vromans
 ISBN 978-1-4493-0370-9 [5th edition July 2011]
 ISBN 978-1-4493-0813-1 [ebook]
 https://www.oreilly.com/library/view/-/9781449311186/
 ISBN 4-87311-031-9 (第 3 版日本語版)
 https://www.oreilly.co.jp/books/4873110319/

=item I<Perl Debugger Pocket Reference>

 by Richard Foley
 ISBN 978-0-596-00503-0 [1st edition January 2004]
 ISBN 978-0-596-55625-9 [ebook]
 https://www.oreilly.com/library/view/-/9781449311186/

=item I<Regular Expression Pocket Reference>

(I<正規表現デスクトップリファレンス>)

=begin original

 by Tony Stubblebine
 ISBN 978-0-596-51427-3 [2nd edition July 2007]
 ISBN 978-0-596-55782-9 [ebook]
 https://www.oreilly.com/library/view/-/9780596514273/

=end original

 by Tony Stubblebine
 ISBN 978-0-596-51427-3 [2nd edition July 2007]
 ISBN 978-0-596-55782-9 [ebook]
 https://www.oreilly.com/library/view/-/9780596514273/
 ISBN 4-87311-170-6 (日本語版)
 https://www.oreilly.co.jp/books/4873111706/

=back

=head2 Tutorials

(チュートリアル)

=over 4

=item I<Beginning Perl>

=begin original

(There are 2 books with this title)

=end original

(同じ題名の本が 2 冊あります)

 by Curtis 'Ovid' Poe
 ISBN 978-1-118-01384-7
 https://www.wiley.com/en-ie/Beginning+Perl-p-9781118235638

 by James Lee
 ISBN 1-59059-391-X [3rd edition April 2010 & ebook]
 https://www.apress.com/9781430227939

=item I<Learning Perl> (the "Llama Book")

(I<初めての Perl> (リャマ本))

=begin original

 by Randal L. Schwartz, Tom Phoenix, and brian d foy
 ISBN 978-1-4493-0358-7 [6th edition June 2011]
 ISBN 978-1-4493-0458-4 [ebook]
 https://www.learning-perl.com/

=end original

 by Randal L. Schwartz, Tom Phoenix, and brian d foy
 ISBN 978-1-4493-0358-7 [6th edition June 2011]
 ISBN 978-1-4493-0458-4 [ebook]
 https://www.learning-perl.com/
 ISBN 978-4-87311-567-2 (日本語版)
 https://www.oreilly.co.jp/books/9784873115672/

=item I<Intermediate Perl> (the "Alpaca Book")

(I<続・初めての Perl 改訂版> (アルパカ本))

=begin original

 by Randal L. Schwartz and brian d foy, with Tom Phoenix
         foreword by Damian Conway
 ISBN 978-1-4493-9309-0 [2nd edition August 2012]
 ISBN 978-1-4493-0459-1 [ebook]
 https://www.intermediateperl.com/

=end original

 by Randal L. Schwartz and brian d foy, with Tom Phoenix
         foreword by Damian Conway
 ISBN 978-1-4493-9309-0 [2nd edition August 2012]
 ISBN 978-1-4493-0459-1 [ebook]
 https://www.intermediateperl.com/
 ISBN 978-4-87311-628-0 (日本語版)
 https://www.oreilly.co.jp/books/9784873116280/

=item I<Mastering Perl>

(I<マスタリング Perl>)

=begin original

    by brian d foy
 ISBN 9978-1-4493-9311-3 [2nd edition January 2014]
 ISBN 978-1-4493-6487-8 [ebook]
 https://www.masteringperl.org/

=end original

    by brian d foy
 ISBN 9978-1-4493-9311-3 [2nd edition January 2014]
 ISBN 978-1-4493-6487-8 [ebook]
 https://www.masteringperl.org/
 ISBN 978-4-87311-397-5 (日本語版)
 https://www.oreilly.co.jp/books/9784873113975/

=item I<Effective Perl Programming>

 by Joseph N. Hall, Joshua A. McAdams, brian d foy
 ISBN 0-321-49694-9 [2nd edition 2010]
 https://www.effectiveperlprogramming.com/

=back

=head2 Task-Oriented

(タスク指向)

=over 4

=item I<Writing Perl Modules for CPAN>

 by Sam Tregar
 ISBN 1-59059-018-X [1st edition August 2002 & ebook]
 https://www.apress.com/9781590590188>

=item I<The Perl Cookbook>

(I<Perl クックブック>)

=begin original

 by Tom Christiansen and Nathan Torkington,
     with Foreword by Larry Wall
 ISBN 978-0-596-00313-5 [2nd Edition August 2003]
 ISBN 978-0-596-15888-0 [ebook]
 https://www.oreilly.com/library/view/-/0596003137/

=end original

 by Tom Christiansen and Nathan Torkington,
     with Foreword by Larry Wall
 ISBN 978-0-596-00313-5 [2nd Edition August 2003]
 ISBN 978-0-596-15888-0 [ebook]
 https://www.oreilly.com/library/view/-/0596003137/
 ISBN 4-87311-202-8 (日本語版第 1 巻)
 https://www.oreilly.co.jp/books/4873112028/
 ISBN 4-87311-203-6 (日本語版第 2 巻)
 https://www.oreilly.co.jp/books/4873112036/

=item I<Automating System Administration with Perl>

 by David N. Blank-Edelman
 ISBN 978-0-596-00639-6 [2nd edition May 2009]
 ISBN 978-0-596-80251-6 [ebook]
 https://www.oreilly.com/library/view/-/9780596801892/

=item I<Real World SQL Server Administration with Perl>

 by Linchi Shea
 ISBN 1-59059-097-X [1st edition July 2003 & ebook]
 https://www.apress.com/9781590590973

=back

=head2 Special Topics

(特定のトピック)

=over 4

=item I<Regular Expressions Cookbook>

(I<正規表現クックブック>)

=begin original

 by Jan Goyvaerts and Steven Levithan
 ISBN 978-1-4493-1943-4 [2nd edition August 2012]
 ISBN 978-1-4493-2747-7 [ebook]
 https://shop.oreilly.com/product/0636920023630.do

=end original

 by Jan Goyvaerts and Steven Levithan
 ISBN 978-1-4493-1943-4 [2nd edition August 2012]
 ISBN 978-1-4493-2747-7 [ebook]
 https://shop.oreilly.com/product/0636920023630.do
 ISBN 978-4-87311-450-7 (日本語版)
 https://www.oreilly.co.jp/books/9784873114507/

=item I<Programming the Perl DBI>

 by Tim Bunce and Alligator Descartes
 ISBN 978-1-56592-699-8 [February 2000]
 ISBN 978-1-4493-8670-2 [ebook]
 https://www.oreilly.com/library/view/-/1565926994/

=item I<Perl Best Practices>

(I<Perl ベストプラクティス>)

=begin original

 by Damian Conway
 ISBN 978-0-596-00173-5 [1st edition July 2005]
 ISBN 978-0-596-15900-9 [ebook]
 https://www.oreilly.com/library/view/-/0596001738/

=end original

 by Damian Conway
 ISBN 978-0-596-00173-5 [1st edition July 2005]
 ISBN 978-0-596-15900-9 [ebook]
 https://www.oreilly.com/library/view/-/0596001738/
 ISBN 4-87311-300-8 (日本語版)
 https://www.oreilly.co.jp/books/4873113008/

=item I<Higher-Order Perl>

 by Mark-Jason Dominus
 ISBN 1-55860-701-3 [1st edition March 2005]
 free ebook https://hop.perl.plover.com/book/
 https://hop.perl.plover.com/

=item I<Mastering Regular Expressions>

(I<詳説 正規表現>)

=begin original

 by Jeffrey E. F. Friedl
 ISBN 978-0-596-52812-6 [3rd edition August 2006]
 ISBN 978-0-596-55899-4 [ebook]
 https://learning.oreilly.com/library/view/-/0596528124/

=end original

 by Jeffrey E. F. Friedl
 ISBN 978-0-596-52812-6 [3rd edition August 2006]
 ISBN 978-0-596-55899-4 [ebook]
 https://learning.oreilly.com/library/view/-/0596528124/
 ISBN 978-4-87311-359-3 (日本語版)
 https://www.oreilly.co.jp/books/9784873113593/

=item I<Network Programming with Perl>

(I<Perlネットワークプログラミング>)

=begin original

 by Lincoln Stein
 ISBN 0-201-61571-1 [1st edition 2001]
 https://www.oreilly.com/library/view/-/0201615711/

=end original

 by Lincoln Stein
 ISBN 0-201-61571-1 [1st edition 2001]
 https://www.oreilly.com/library/view/-/0201615711/
 ISBN 4894714655 (日本語版)
 https://www.pej-hed.jp/washo/312.html

=item I<Perl Template Toolkit>

 by Darren Chamberlain, Dave Cross, and Andy Wardley
 ISBN 978-0-596-00476-7 [December 2003]
 ISBN 978-1-4493-8647-4 [ebook]
 https://www.oreilly.com/library/view/-/0596004761/

=item I<Object Oriented Perl>

(I<オブジェクト指向 Perl マスターコース>)

=begin original

 by Damian Conway
     with foreword by Randal L. Schwartz
 ISBN 1-884777-79-1 [1st edition August 1999 & ebook]
 https://www.manning.com/conway/

=end original

 by Damian Conway
     with foreword by Randal L. Schwartz
 ISBN 1-884777-79-1 [1st edition August 1999 & ebook]
 https://www.manning.com/conway/
 ISBN 4894713004 (日本語版)
 https://www.pej-hed.jp/washo/195.html

=item I<Data Munging with Perl>

(I<Perl データマンジング>)

=begin original

 by Dave Cross
 ISBN 1-930110-00-6 [1st edition 2001 & ebook]
 https://www.manning.com/cross>

=end original

 by Dave Cross
 ISBN 1-930110-00-6 [1st edition 2001 & ebook]
 https://www.manning.com/cross>
 ISBN 4894715589 (日本語版)
 https://www.pej-hed.jp/washo/376.html

=item I<Mastering Perl/Tk>

 by Steve Lidie and Nancy Walsh
 ISBN 978-1-56592-716-2 [1st edition January 2002]
 ISBN 978-0-596-10344-6 [ebook]
 https://www.oreilly.com/library/view/-/1565927168/

=item I<Extending and Embedding Perl>

 by Tim Jenness and Simon Cozens
 ISBN 1-930110-82-0 [1st edition August 2002 & ebook]
 https://www.manning.com/jenness

=item I<Pro Perl Debugging>

 by Richard Foley with Andy Lester
 ISBN 1-59059-454-1 [1st edition July 2005 & ebook]
 https://www.apress.com/9781590594544

=back

=head2 Free (as in beer) books

(自由に読める本)

=begin original

Some of these books are available as free downloads.

=end original

これらの本の一部は自由にダウンロードできます。

I<Higher-Order Perl>: L<https://hop.perl.plover.com/>

I<Modern Perl>: L<https://onyxneon.com/books/modern_perl/>

=head2 Other interesting, non-Perl books

(その他の興味深い、非 Perl の本)

=begin original

You might notice several familiar Perl concepts in this collection of
ACM columns from Jon Bentley. The similarity to the title of the major
Perl book (which came later) is not completely accidental:

=end original

いくつかの Perl のコンセプトが、この Jon Bentley による ACM コラムの
コレクションにあることに気付くかもしれません。
(後から出た) 有名な Perl 本のタイトルとの類似性は完全に偶然ではありません:

=over 4

=item I<Programming Pearls>

(I<珠玉のプログラミング>)

=begin original

 by Jon Bentley
 ISBN 978-0-201-65788-3 [2nd edition, October 1999]

=end original

 by Jon Bentley
 ISBN 978-0-201-65788-3 [2nd edition, October 1999]
 http://www.pej-hed.jp/washo/159.html [日本語版]

=item I<More Programming Pearls>

(I<プログラマのうちあけ話>)

=begin original

 by Jon Bentley
 ISBN 0-201-11889-0 [January 1988]

=end original

 by Jon Bentley
 ISBN 0-201-11889-0 [January 1988]
 http://www.yfcbookshelf.com/programming%27s%20books2.htm [日本語版]

=back

=head2 A note on freshness

(鮮度に関する注意)

=begin original

Each version of Perl comes with the documentation that was current at
the time of release. This poses a problem for content such as book
lists. There are probably very nice books published after this list
was included in your Perl release, and you can check the latest
released version at L<http://perldoc.perl.org/perlbook.html> .

=end original

それぞれのバージョンの Perl はリリースの時点で最新の文書を同梱しています。
これは、本の一覧のような内容について問題を引き起こします。
Perl のリリースに含まれているこの一覧が含まれた後に出版されたとてもよい
本がおそらくあるので、最新リリース版を
L<https://perldoc.perl.org/perlbook.html> でチェックできます。

=begin original

Some of the books we've listed appear almost ancient in internet
scale, but we've included those books because they still describe the
current way of doing things. Not everything in Perl changes every day.
Many of the beginner-level books, too, go over basic features and
techniques that are still valid today. In general though, we try to
limit this list to books published in the past five years.

=end original

ここで挙げた本の一部はインターネットの尺度ではほとんど古典ですが、今でも
物事を為すための現在の方法を記述しているのでこれらの本を含めています。
Perl の全てが毎日変わっているわけではありません。
多くの初心者レベルの本も同様で、基本的な機能とテクニックは現在でも有効です。
しかし、一般的には、過去 5 年以内に出版された本に制限しようとしています。

=head2 Get your book listed

(あなたの本を一覧に載せるには)

=begin original

If your Perl book isn't listed and you think it should be, let us know.
L<mailto:perl5-porters@perl.org>

=end original

あなたの Perl 本が一覧になく、ここにあるべきだと思うなら、私たちに
教えてください。
L<mailto:perl5-porters@perl.org>

=cut

=begin meta

Translate: SHIRAKATA Kentaro <argrath@ub32.org>
Status: completed

=end meta

