=encoding utf-8

=head1 名前

YAML::Error - Error formatting class for YAML modules

YAML::Error - YAML モジュール群用エラー整形クラス

=head1 概要

    $self->die('YAML_PARSE_ERR_NO_ANCHOR', $alias);
    $self->warn('YAML_LOAD_WARN_DUPLICATE_KEY');

=head1 説明

This module provides a C<die> and a C<warn> facility.

このモジュールは C<die> 及び C<warn> の機能を提供しています.

=head1 著者

Ingy dE<ouml>t Net <ingy@cpan.org>


=head1 著作権

Copyright (c) 2006. Ingy dE<ouml>t Net. All rights reserved.


This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.

このプログラムはフリーソフトウェアです。あなたは Perl と同じ
ライセンスの 元で再配布及び変更を行うことが出来ます.

See L<http://www.perl.com/perl/misc/Artistic.html>

参考 L<http://www.perl.com/perl/misc/Artistic.html>

