
=encoding euc-jp

=head1 名前

 AnyData::Format::Ini - iniファイルへのtieされたハッシュとDBI/SQLによるアクセス

=head1 概要

 use AnyData;
 my $table = adHash( 'Ini', $filename,'r',$flags );
 while (my $row = each %$table) {
     print $row->{name},"\n" if $row->{country} =~ /us|mx|ca/;
 }
 # ... そのほかのtieされたハッシュの操作

 または

 use DBI
 my $dbh = DBI->connect('dbi:AnyData:');
 $dbh->func('table1','Init', $filename,$flags,'ad_catalog');
 my $hits = $dbh->selectall_arrayref( qq{
     SELECT name FROM table1 WHERE country = 'us'
 });
 # ... その他のDBI/SQL操作

=head1 説明

これは単純な name=value形式のIniファイルのためのパーサーです。すぐにセクションを
持ったファイルも扱うようになるでしょう。

さらなる詳細はAnyData.pmとDBD::AnyData.pmのドキュメントをご覧ください。 

=head1 作者と著作権(=AUTHOR & COPYRIGHT)

copyright 2000, Jeff Zucker <jeff@vpservices.com>
all rights reserved

=head1 翻訳者

川合孝典(GCD00051@nifty.ne.jp)

