=head1 名前

  Net::Server::Proto::UDP - adp0 - Net::Server UDP protocol.

  Net::Server::Proto::UDP - adp0 - Net::Server UDPプロトコル

=head1 概要

See L<Net::Server::Proto>.

L<Net::Server::Proto>を参照。

=head1 説明

Protocol module for Net::Server.  This module implements the
SOCK_DGRAM socket type under INET (also known as UDP).
See L<Net::Server::Proto>.

Net::Server用のプロトコルモジュール。このモジュールは
INETの下でSOCK_DGRAMソケット型（UDPとして知られている）
を実装する。L<Net::Server::Proto>を参照。

=head1 パラメータ

The following paramaters may be specified in addition to
normal command line parameters for a Net::Server.  See
L<Net::Server> for more information on reading arguments.

Net::Serverの通常のコマンドライン引数に加えて、以下の
パラメータを指定できる。引数の詳細については
L<Net::Server>を参照のこと。

=over 4

=item udp_recv_len

Specifies the number of bytes to read from the UDP connection
handle.  Data will be read into $self->{server}->{udp_data}.
Default is 4096.  See L<IO::Socket::INET> and L<recv>.

UDPコネクションハンドルから読み取るバイト数を指定する。
データは$self->{server}->{udp_data}に読み取られる。
デフォルトは4096。L<IO::Socket::INET>とL<recv>を参照。

=item udp_recv_flags

See L<recv>.  Default is 0.

L<recv>を見よ。デフォルトは0。

=back

=head1 パラメータ早見表

  Key               Value                    Default

  ## UDP プロトコルパラメータ
  udp_recv_len      \d+                      4096
  udp_recv_flags    \d+                      0

=head1 LICENCE

Distributed under the same terms as Net::Server

