
=encoding utf8

=head1 NAME

=begin original

HTTP::WebTest::Plugin::DefaultReport - Default test report plugin.

=end original

HTTP::WebTest::Plugin::DefaultReport - デフォルトのテストレポートプラグイン

=head1 SYNOPSIS

=begin original

Not Applicable

=end original

なし.

=head1 DESCRIPTION

=begin original

This plugin is the default test report plugin.  It builds a simple text
report.

=end original

このプラグインはデフォルトのテストレポートプラグインです. 
これは簡単なテキストレポートを生成します.

=head1 TEST PARAMETERS

(テストパラメータ)

=head2 default_report

I<GLOBAL PARAMETER>


=begin original

This parameter controls whether the default report plugin is used for
test report creation.  Value C<yes> means that default report plugin
will be used, value C<no> means that it will not.
It can also be used to disable all output 
(i.e. if this parameter has value C<no> and no other report plugins
are loaded).

=end original

このパラメータではデフォルトレポートプラグインを使ってテストレポートを
生成するかどうかを制御します. 値 C<yes> はデフォルトレポートプラグイン
の使用を意味します. 値 C<no> のと気は使用しません. 
これによってなにも出力しないようにもできます
(すなわちこのパラメータを値 C<no> にして他のレポートプラグインをロード
しなかったとき).

=head3 Allowed values

(使用可能な値)

C<yes>, C<no>


=head3 Default value

(デフォルト値)

C<yes>


=head2 test_name

=begin original

Name associated with this URL in the test report and error messages.

=end original

URL に関連づけられた名前. テストレポートやエラーメッセ時で使われます.

=head2 show_headers

=begin original

Include request and response headers in the test report.

=end original

テストレポートのリクエストヘッダ及びレスポンスヘッダを含めるかを
設定します.

=head3 Allowed values

(使用可能な値)

C<yes>, C<no>


=head3 Default value

(デフォルト値)

C<no>


=head2 show_html

=begin original

Include content of HTTP response in the test report.

=end original

テストレポートに HTTP レスポンスを含めるかを設定します.

=head3 Allowed values

(使用可能な値)

C<yes>, C<no>


=head3 Default value

(デフォルト値)

C<no>


=head2 show_cookies

=begin original

Option to display any cookies sent or received.

=end original

送受信したクッキーを表示するかを設定します.

=head3 Allowed values

(使用可能な値)

C<yes>, C<no>


=head3 Default value

(デフォルト値)

C<no>


=head2 terse

=begin original

Option to display shorter test report.

=end original

短いテストレポートを表示するかを設定します.

=over 4

=item * summary

(summary (要約))

=begin original

Only a one-line summary for each URL

=end original

各 URL の１行要約のみ

=item * failed_only

=begin original

Only tests that failed and the summary

=end original

失敗したテストと要約のみ

=item * no

=begin original

Show all tests and the summary

=end original

全てのテストと要約を表示

=over 8 

=item Default value

デフォルト値

C<no>

=back

=back

=head1 COPYRIGHT

Copyright (c) 2000-2001 Richard Anderson.  All rights reserved.


Copyright (c) 2001-2003 Ilya Martynov.  All rights reserved.


=begin original

This program is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=end original

このプログラムはフリーソフトです. このプログラムは Perl 自身と同じ条件下で
再配布・改変可能です.

=head1 SEE ALSO

L<HTTP::WebTest|HTTP::WebTest>


L<HTTP::WebTest::API|HTTP::WebTest::API>


L<HTTP::WebTest::Plugin|HTTP::WebTest::Plugin>


L<HTTP::WebTest::Plugins|HTTP::WebTest::Plugins>


