=head1 名前

Crypt::Cracklib - Alec MuffettのCracklibへのPerlインターフェース

=head1 概要

  use Crypt::Cracklib;
  
  my $reason = fascist_check($password, $dictionary);

  print "Ok"  if  check($password, $dictionary);
  print "Bad" if !check($password, $dictionary);

  $Crypt::Cracklib::DICT = '/path/to/cracklib/dictionary';
  my $reason = fascist_check($password);

=head1 説明

これはAlec Muffettの Crack ライブラリへの簡単なインターフェースです。

=head1 Exportされる定数

  MAXBLOCKLEN
  MAXWORDLEN
  NUMWORDS
  PFOR_FLUSH
  PFOR_USEHWMS
  PFOR_WRITE
  PIH_MAGIC
  STRINGSIZE
  TRUNCSTRINGSIZE

=head1 作者

Daniel <daniel-cpan-cracklib@electricrain.com>

=head1 参考資料

perl(1).

=head1 翻訳者

川合孝典 (GCD00051@nifty.ne.jp)

