=head1 NAME

XML::FOAF::Person - FOAF ファイルの Person クラス

=head1 SYNOPSIS

    my $person = $foaf->person;
    print $person->mbox, "\n";
    my $people = $foaf->knows;

=head1 DESCRIPTION

I<XML::FOAF::Person> represents a I<Person> class in a FOAF file.

I<XML::FOAF::Person> は FOAF ファイルの I<Person> クラスを表現します。

=head1 USAGE

You can use any property as a method name and call it on a I<XML::FOAF::Person>
object. For example:

メソッド名としてプロパティを用いることができ、I<XML::FOAF::Person>
オブジェクトのメソッドを呼びます。

    my $email = $person->mbox;
    my $name = $person->name;

In addition to this, some methods with special beheavior are defined below:

それに加えて、次のような特別なメソッドを定義します。

=head2 $person->knows

Returns a reference to an array of I<XML::FOAF::Person> objects representing
the people that I<$person> knows.

I<$person> が知っている人物を表現した I<XML::FOAF::Person> オブジェクトの
配列リファレンスを返します。

=head1 AUTHOR & COPYRIGHT

Please see the I<XML::FOAF> manpage for author, copyright, and license
information.

=head1 翻訳について

翻訳者：IWAI, Masaharu E<lt>iwai@alib.jpE<gt>

Perlドキュメント日本語訳 Project にて、
Perlモジュール、ドキュメントの翻訳を行っております。

L<http://perldocjp.sourceforge.jp/>,
L<http://freeml.com/ctrl/html/MLInfoForm/perldocjp@freeml.com>,
L<http://perldoc.jp/>


=cut

