=encoding utf-8

=head1 NAME

=begin original

Term::Encoding - Detect encoding of the current terminal

=end original

Term::Encoding - 現在のターミナルのエンコーディングの検出

=head1 SYNOPSIS

=begin original

  use Term::Encoding qw(term_encoding);
  my $encoding = term_encoding;

  # ditto without exporting function
  use Term::Encoding;
  my $encoding = Term::Encoding::get_encoding();

=end original

  use Term::Encoding qw(term_encoding);
  my $encoding = term_encoding;

  # 関数をエクスポートしなくても, 同じことができます.
  use Term::Encoding;
  my $encoding = Term::Encoding::get_encoding();

=head1 DESCRIPTION

=begin original

Term::Encoding is a simple module to detect an encoding the current
terminal expects, in various ways.

=end original

Term::Encodingは様々な方法で現在のターミナルのエンコーディングを検出するための
シンプルなモジュールです.

=head1 AUTHORS

Tatsuhiko Miyagawa E<lt>miyagawa@bulknews.netE<gt>

Audrey Tang E<lt>audreyt@audreyt.orgE<gt>

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=head1 SEE ALSO

L<Locale::Maketext::Lexicon>

=cut
