
=encoding euc-jp

=head1 NAME

=begin original

perldelta - what is new for perl v5.30.1

=end original

perl5301delta - perl v5.30.1 での変更点

=head1 DESCRIPTION

=begin original

This document describes differences between the 5.30.0 release and the 5.30.1
release.

=end original

この文書は 5.30.0 リリースと 5.30.1 リリースの変更点を記述しています。

=begin original

If you are upgrading from an earlier release such as 5.29.0, first read
L<perl5300delta>, which describes differences between 5.29.0 and 5.30.0.

=end original

5.29.0 のような以前のリリースから更新する場合は、まず 5.29.0 と
5.30.0 の違いについて記述している L<perl5300delta> を読んでください。

=head1 Incompatible Changes

(互換性のない変更)

=begin original

There are no changes intentionally incompatible with 5.30.1.  If any exist,
they are bugs, and we request that you submit a report.  See
L</Reporting Bugs> below.

=end original

故意に、5.30.1 から互換性がなくなるようにした変更はありません。
もし 5.30.1 との互換性がなければ、それはバグですので、報告をお願いします。
以下の L</Reporting Bugs> を参照してください。

=head1 Modules and Pragmata

(モジュールとプラグマ)

=head2 Updated Modules and Pragmata

(更新されたモジュールとプラグマ)

=over 4

=item *

=begin original

L<Module::CoreList> has been upgraded from version 5.20190522 to 5.20191110.

=end original

L<Module::CoreList> はバージョン 5.20190522 から 5.20191110 に更新されました。

=back

=head1 Documentation

(文書)

=head2 Changes to Existing Documentation

(既存の文書の変更)

=begin original

We have attempted to update the documentation to reflect the changes listed in
this document.  If you find any we have missed, send email to
L<perlbug@perl.org|mailto:perlbug@perl.org>.

=end original

私たちはこの文書で挙げられた変更を反映するように文書を更新しようとしています。
もし抜けている物を発見したら、
L<perlbug@perl.org|mailto:perlbug@perl.org> にメールしてください。

=begin original

Additionally, documentation has been updated to reference GitHub as the new
canonical repository and to describe the new GitHub pull request workflow.

=end original

さらに、GitHub を新しい中央リポジトリとして参照することと、新しい
GitHub プルリクエストワークフローを記述するために更新しています。

=head1 Configuration and Compilation

(設定とコンパイル)

=over 4

=item *

=begin original

The C<ECHO> macro is now defined.  This is used in a C<dtrace> rule that was
originally changed for FreeBSD, and the FreeBSD make apparently predefines it.
The Solaris make does not predefine C<ECHO> which broke this rule on Solaris.
L<[perl #17057]|https://github.com/perl/perl5/issues/17057>

=end original

C<ECHO> マクロが定義されました。
これは、もともと FreeBSD のために変更する C<dtrace> 規則で使われていて、
FreeBSD の make は事前定義しているようです。
Solaris の make は C<ECHO> は事前定義していないので、Solaris では
この規則が壊れていました。
L<[perl #17057]|https://github.com/perl/perl5/issues/17057>

=back

=head1 Testing

(テスト)

=begin original

Tests were added and changed to reflect the other additions and changes in this
release.

=end original

このリリースのその他の追加と変更を反映するようにテストを追加および
変更しました。

=head1 Platform Support

(プラットフォーム対応)

=head2 Platform-Specific Notes

(プラットフォーム固有の注意)

=over 4

=item Win32

=begin original

The locale tests could crash on Win32 due to a Windows bug, and separately due
to the CRT throwing an exception if the locale name wasn't validly encoded in
the current code page.

=end original

ロケールのテストは Windows のバグのために、およびロケール名が現在の
コードページで正当にエンコードされていない場合に CRT が例外を投げるために、
Win32 でクラッシュすることがありました。

=begin original

For the second we now decode the locale name ourselves, and always decode it as
UTF-8.

=end original

二番目に対応するため、ロケール名を自分自身でデコードするように、そして
UTF-8 としてデコードするようになりました。

L<[perl #16922]|https://github.com/perl/perl5/issues/16922>

=back

=head1 Selected Bug Fixes

(バグ修正の抜粋)

=over 4

=item *

=begin original

Setting C<$)> now properly sets supplementary group ids, if you have the
necessary privileges.
L<[perl #17031]|https://github.com/perl/perl5/issues/17031>

=end original

C<$)> を設定するとき、適切な権限がある場合は補助グループ ID を
適切に設定するようになりました。
L<[perl #17031]|https://github.com/perl/perl5/issues/17031>

=item *

=begin original

C<readline @foo> now evaluates C<@foo> in scalar context.  Previously, it would
be evaluated in list context, and since readline() pops only one argument from
the stack, the stack could underflow, or be left with unexpected values on it.
L<[perl #16929]|https://github.com/perl/perl5/issues/16929>

=end original

C<readline @foo> はスカラコンテキストで C<@foo> を評価するようになりました。
以前は、これはリストコンテキストで評価され、
readline() はスタックから一つしか引数をポップしないので、
スタックがアンダーフローしたり、想定しない値を残したりすることがありました。
L<[perl #16929]|https://github.com/perl/perl5/issues/16929>

=item *

=begin original

sv_gets() now recovers better if the target SV is modified by a signal handler.
L<[perl #16960]|https://github.com/perl/perl5/issues/16960>

=end original

ターゲットの SV がシグナルハンドラによって変更された場合、
sv_gets() はよりよく回復するようになりました。
L<[perl #16960]|https://github.com/perl/perl5/issues/16960>

=item *

=begin original

Matching a non-C<SVf_UTF8> string against a regular expression containing
Unicode literals could leak an SV on each match attempt.
L<[perl #17140]|https://github.com/perl/perl5/issues/17140>

=end original

非 C<SVf_UTF8> 文字列を Unicode リテラルを含む正規表現でマッチングすると、
マッチングする毎に SV をリークすることがありました。
L<[perl #17140]|https://github.com/perl/perl5/issues/17140>

=item *

=begin original

C<< sprintf("%.*a", -10000, $x) >> would cause a buffer overflow due to
mishandling of the negative precision value.
L<[perl #16942]|https://github.com/perl/perl5/issues/16942>

=end original

C<< sprintf("%.*a", -10000, $x) >> は、負の精度値の扱いを間違っていたために
バッファオーバーフローを引き起こしていました。
L<[perl #16942]|https://github.com/perl/perl5/issues/16942>

=item *

=begin original

C<scalar()> on a reference could cause an erroneous assertion failure during
compilation.
L<[perl #16969]|https://github.com/perl/perl5/issues/16969>

=end original

リファレンスに対する C<scalar()> はコンパイル中に間違ったアサーション失敗を
引き起こすことがありました。
L<[perl #16969]|https://github.com/perl/perl5/issues/16969>

=back

=head1 Acknowledgements

=begin original

Perl 5.30.1 represents approximately 6 months of development since Perl 5.30.0
and contains approximately 4,700 lines of changes across 67 files from 14
authors.

=end original

Perl 5.30.1 は、Perl 5.30.0 以降、14 人の作者によって、
67 のファイルに約 4,700 行の変更を加えて、
約 6 ヶ月開発されてきました。

=begin original

Excluding auto-generated files, documentation and release tools, there were
approximately 910 lines of changes to 20 .pm, .t, .c and .h files.

=end original

自動生成ファイル、文書、リリースツールを除くと、20 の .pm, .t, .c,
.h ファイルに約 910 行の変更を加えました。

=begin original

Perl continues to flourish into its fourth decade thanks to a vibrant community
of users and developers.  The following people are known to have contributed
the improvements that became Perl 5.30.1:

=end original

Perl は、活気のあるユーザーと開発者のコミュニティのおかげで 30 年を超えて
繁栄しています。
以下の人々が、Perl 5.30.1 になるための改良に貢献したことが分かっています:

Chris 'BinGOs' Williams, Dan Book, David Mitchell, Hugo van der Sanden, James E
Keenan, Karen Etheridge, Karl Williamson, Manuel Mausz, Max Maischein, Nicolas
R., Sawyer X, Steve Hay, Tom Hukins, Tony Cook.

=begin original

The list above is almost certainly incomplete as it is automatically generated
from version control history.  In particular, it does not include the names of
the (very much appreciated) contributors who reported issues to the Perl bug
tracker.

=end original

これはバージョンコントロール履歴から自動的に生成しているので、ほぼ確実に
不完全です。
特に、Perl バグトラッカーに問題を報告をしてくれた (とてもありがたい)貢献者の
名前を含んでいません。

=begin original

Many of the changes included in this version originated in the CPAN modules
included in Perl's core.  We're grateful to the entire CPAN community for
helping Perl to flourish.

=end original

このバージョンに含まれている変更の多くは、Perl コアに含まれている CPAN
モジュール由来のものです。
私たちは Perl の発展を助けている CPAN コミュニティ全体に感謝します。

=begin original

For a more complete list of all of Perl's historical contributors, please see
the F<AUTHORS> file in the Perl source distribution.

=end original

全ての Perl の歴史的な貢献者のより完全な一覧については、どうか Perl ソース
配布に含まれている F<AUTHORS> を参照してください。

=head1 Reporting Bugs

(バグ報告)

=begin original

If you find what you think is a bug, you might check the perl bug database at
L<https://rt.perl.org/>.  There may also be information at
L<http://www.perl.org/>, the Perl Home Page.

=end original

もしバグと思われるものを見つけたら、 L<https://rt.perl.org/> にある perl バグ
データベースを確認してください。
Perl ホームページ、L<http://www.perl.org/> にも情報があります。

=begin original

If you believe you have an unreported bug, please run the L<perlbug> program
included with your release.  Be sure to trim your bug down to a tiny but
sufficient test case.  Your bug report, along with the output of C<perl -V>,
will be sent off to perlbug@perl.org to be analysed by the Perl porting team.

=end original

もしまだ報告されていないバグだと確信したら、そのリリースに含まれている
L<perlbug> プログラムを実行してください。
バグの再現スクリプトを十分小さく、しかし有効なコードに切りつめることを
意識してください。
バグレポートは C<perl -V> の出力と一緒に perlbug@perl.org に送られ
Perl porting チームによって解析されます。

=begin original

If the bug you are reporting has security implications which make it
inappropriate to send to a publicly archived mailing list, then see
L<perlsec/SECURITY VULNERABILITY CONTACT INFORMATION> for details of how to
report the issue.

=end original

報告しようとしているバグがセキュリティに関するもので、公開されている
メーリングリストに送るのが不適切なものなら、バグの報告方法の詳細について
L<perlsec/SECURITY VULNERABILITY CONTACT INFORMATION> を参照してください。

=head1 Give Thanks

(感謝を伝える)

=begin original

If you wish to thank the Perl 5 Porters for the work we had done in Perl 5, you
can do so by running the C<perlthanks> program:

=end original

もし Perl 5 でなされた作業について Perl 5 Porters に感謝したいと考えたなら、
C<perlthanks> プログラムを実行することでそうできます:

    perlthanks

=begin original

This will send an email to the Perl 5 Porters list with your show of thanks.

=end original

これは Perl 5 Porters メーリングリストにあなたの感謝の言葉をメールします。

=head1 SEE ALSO

=begin original

The F<Changes> file for an explanation of how to view exhaustive details on
what changed.

=end original

変更点の完全な詳細を見る方法については F<Changes> ファイル。

=begin original

The F<INSTALL> file for how to build Perl.

=end original

Perl のビルド方法については F<INSTALL> ファイル。

=begin original

The F<README> file for general stuff.

=end original

一般的なことについては F<README> ファイル。

=begin original

The F<Artistic> and F<Copying> files for copyright information.

=end original

著作権情報については F<Artistic> 及び F<Copying> ファイル。

=begin meta

Translate: SHIRAKATA Kentaro <argrath@ub32.org>
Status: completed

=end meta

=cut

